# 定义开发目录
INCDIR = ../include/
OBJDIR = $(CMM2003LIBDIR)

# 定义头文件目录清单
# 顺序应该是：
# 通用模块头文件目录/当前开发环境头文件目录/本工程的头文件目录

INCL = -I $(INCDIR) -I $(CMM2003INCDIR)	-I/usr/local/include/PCSC/

#传给脚本的参数
SLP1 = "$*.o"	"$@ $*.o"	$@
# 这个编译开关必须增加
DEFINES = -D _UNIX $(OSSPEC)

COMPILE	= $(CC) $(DEFINES) $(INCL) -c

VPATH	= $(OBJDIR)

srcs	= $(wildcard *.c)
objs =	$(patsubst %.c,%.o,$(srcs)) 

objs +=	cardReader

all:	makeall

makeall:	$(objs)

.SUFFIXES:.c.o
%.o:%.c
	@echo "CC $(DEFINES) $@	$<"
	$(COMPILE) $< -o $@

libs0110 = 	cardReader.o			\
		$(OBJDIR)unionSmartCard1.0.o	\
		-L/usr/local/lib/ -lpcsclite

cardReader:
		@echo "building...	$@"
		@$(CC) $(DEFINES) -o $@ $(libs0110) $(OSSPECLIBS)

.PHONY: clean show

clean:
	$(RM) $(addprefix $(OBJDIR),$(objs))
	$(RM) cardReader
	
show:
	make -v
	@echo '=============================================================='
	@echo 'srcs	:' $(srcs)
	@echo 'objs	:' $(objs)
	@echo 'INCL	:' $(INCL)
	@echo 'COMPILE	:' $(COMPILE)
	
