# 配置说明
# 第一个域: 如中括号括起来，为菜单的提示信息
#     当菜单提示信息为null时，则为空白行菜单
# 最后一个域为makefile文件名,支持多个，用,号分隔
[基础APP程序]           	appTask.mk
[essc2 APP程序]			appTask-essc2x.mk
[essc3 APP程序]			appTask-essc3x.mk

[null]
[管理类程序]            	commBins.mk
[工具类程序]            	tools.mk
[系统服务类程序]        	sysSvr.mk
[input3XOr4XDesKeyTo5XDB.mk]	input3XOr4XDesKeyTo5XDB.mk
[keyDBManagerTool.mk]		keyDBManagerTool.mk
[keySynchro.mk]			keySynchro.mk

[null]
[界面服务SO]			service-ui.mk
[标准服务SO]			service-so.mk
[IC卡类SO]			service-icCard.mk
[大连农商服务SO]		service-dlnx.mk

# 配置说明
# 第一个域: 如中括号括起来，为菜单的提示信息
#     当菜单提示信息为null时，则为空白行菜单
# 最后一个域为makefile文件名,支持多个，用,号分隔
