// Automatically generated codes
// Generated Date and Time 20100323000015
// Generated by devdep

#ifndef _unionTableDesignDoc_struct_1_0_
#define _unionTableDesignDoc_struct_1_0_
#endif


// 定义表的域名常量
#define conTableDesignDocFldNameProjectID		"projectID"
#define conTableDesignDocFldNameProjectName		"projectName"
#define conTableDesignDocFldNameNameOfModule		"nameOfModule"
#define conTableDesignDocFldNameTableName		"tableName"
#define conTableDesignDocFldNameTableAlais		"tableAlais"
#define conTableDesignDocFldNameResID		"resID"
#define conTableDesignDocFldNameTableType		"tableType"
#define conTableDesignDocFldNameReservedRes		"reservedRes"
#define conTableDesignDocFldNameTBLProperty		"TBLProperty"
#define conTableDesignDocFldNameStoreWay		"storeWay"
#define conTableDesignDocFldNameTBLUseName		"TBLUseName"
#define conTableDesignDocFldNameBranchFldName		"branchFldName"
#define conTableDesignDocFldNameVersion		"version"
#define conTableDesignDocFldNameProjectUpgrade		"projectUpgrade"
#define conTableDesignDocFldNameRemark		"remark"
#define conTableDesignDocFldNameFieldList		"fieldList"
#define conTableDesignDocFldNamePrimaryKey		"primaryKey"
#define conTableDesignDocFldNameUnique1		"unique1"
#define conTableDesignDocFldNameUnique2		"unique2"
#define conTableDesignDocFldNameUnique3		"unique3"
#define conTableDesignDocFldNameUnique4		"unique4"
#define conTableDesignDocFldNameMyKeyGrp1		"myKeyGrp1"
#define conTableDesignDocFldNameForeignTable1		"foreignTable1"
#define conTableDesignDocFldNameForeignKey1		"foreignKey1"
#define conTableDesignDocFldNameMyKeyGrp2		"myKeyGrp2"
#define conTableDesignDocFldNameForeignTable2		"foreignTable2"
#define conTableDesignDocFldNameForeignKey2		"foreignKey2"
#define conTableDesignDocFldNameMyKeyGrp3		"myKeyGrp3"
#define conTableDesignDocFldNameForeignTable3		"foreignTable3"
#define conTableDesignDocFldNameForeignKey3		"foreignKey3"
#define conTableDesignDocFldNameMyKeyGrp4		"myKeyGrp4"
#define conTableDesignDocFldNameForeignTable4		"foreignTable4"
#define conTableDesignDocFldNameForeignKey4		"foreignKey4"
#define conTableDesignDocFldNameOperationList		"operationList"
#define conTableDesignDocFldNameInitValueList		"initValueList"
#define conTableDesignDocFldNameFormMenuItemList		"formMenuItemList"
#define conTableDesignDocFldNameRecMenuItemList		"recMenuItemList"
#define conTableDesignDocFldNameDoubleClickMenuItemList		"doubleClickMenuItemList"
#define conTableDesignDocFldNameCompleteStatus		"completeStatus"
#define conTableDesignDocFldNamePrincipal		"principal"
#define conTableDesignDocFldNameInputTeller		"inputTeller"
#define conTableDesignDocFldNameInputDate		"inputDate"
#define conTableDesignDocFldNameInputTime		"inputTime"
#define conTableDesignDocFldNameUpdateTeller		"updateTeller"
#define conTableDesignDocFldNameUpdateDate		"updateDate"
#define conTableDesignDocFldNameUpdateTime		"updateTime"

/*
*** 结构对应的表信息 ***
表名::          tableDesignDoc
表名宏定义::    conTBLNameTableDesignDoc
表资源宏定义::  conResIDTableDesignDoc
关键字::        tableName,version
*/

// 定义表记录对应的结构
typedef struct
{
	char	projectID[40+1];	// 项目编号
	char	projectName[1024+1];	// 项目名称
	char	nameOfModule[65+1];	// 模块名称
	char	tableName[40+1];	// 表名称
	char	tableAlais[40+1];	// 表别名
	int	resID;	// 资源ID号
	char	tableType[40+1];	// 所属模块
	int	reservedRes;	// 是否保留表
	int	TBLProperty;	// 定义一个表属性
	int	storeWay;	// 定义一个存储实现方式
	int	TBLUseName;	// 定义一个表通用标识
	char	branchFldName[40+1];	// 机构号的域名称
	char	version[40+1];	// 版本号
	char	projectUpgrade[1024+1];	// 项目升级
	char	remark[128+1];	// 128个字符的说明
	char	fieldList[1024+1];	// 域清单
	char	primaryKey[128+1];	// 关键字域
	char	unique1[64+1];	// 唯一值域1
	char	unique2[64+1];	// 唯一值域2
	char	unique3[64+1];	// 唯一值域3
	char	unique4[64+1];	// 唯一值域4
	char	myKeyGrp1[64+1];	// 本表域组1
	char	foreignTable1[40+1];	// 外表1
	char	foreignKey1[64+1];	// 外键域1
	char	myKeyGrp2[64+1];	// 本表域组2
	char	foreignTable2[40+1];	// 外表2
	char	foreignKey2[64+1];	// 外键域2
	char	myKeyGrp3[64+1];	// 本表域组3
	char	foreignTable3[40+1];	// 外表3
	char	foreignKey3[64+1];	// 外键域3
	char	myKeyGrp4[64+1];	// 本表域组4
	char	foreignTable4[40+1];	// 外表4
	char	foreignKey4[64+1];	// 外键域4
	char	operationList[512+1];	// 支持的操作清单
	char	initValueList[128+1];	// 初始值清单
	char	formMenuItemList[256+1];	// 界面菜单项清单
	char	recMenuItemList[256+1];	// 记录菜单项清单
	char	doubleClickMenuItemList[128+1];	// 双击记录菜单项清单
	int	completeStatus;	// 完成状态
	char	principal[40+1];	// 负责人
	char	inputTeller[20+1];	// 记录插入数据库时，系统自动附加的操作员标识
	char	inputDate[8+1];	// 记录插入数据库时，系统自动附加的日期
	char	inputTime[6+1];	// 记录插入数据库时，系统自动附加的时间
	char	updateTeller[20+1];	// 记录修改时，系统自动附加的操作员标识
	char	updateDate[8+1];	// 记录修改时，系统自动附加的日期
	char	updateTime[6+1];	// 记录修改时，系统自动附加的时间
} TUnionTableDesignDoc;
typedef TUnionTableDesignDoc	*PUnionTableDesignDoc;

