// Automatically generated codes
// Generated Date and Time 20100402150724
// Generated by ud090401

#ifndef _unionMainMenu_struct_20090421_
#define _unionMainMenu_struct_20090421_
#endif


// 定义表的域名常量
#define conMainMenuFldNameMainMenuName		"mainMenuName"
#define conMainMenuFldNameMainMenuItemsList		"mainMenuItemsList"
#define conMainMenuFldNameProjectID		"projectID"
#define conMainMenuFldNameUseMenuItemButton		"useMenuItemButton"
#define conMainMenuFldNameUseServerMenu		"useServerMenu"
#define conMainMenuFldNameRemark		"remark"
#define conMainMenuFldNameInputTeller		"inputTeller"
#define conMainMenuFldNameInputDate		"inputDate"
#define conMainMenuFldNameInputTime		"inputTime"
#define conMainMenuFldNameUpdateTeller		"updateTeller"
#define conMainMenuFldNameUpdateDate		"updateDate"
#define conMainMenuFldNameUpdateTime		"updateTime"
#define conMainMenuFldNameIconFileName		"iconFileName"

/*
*** 结构对应的表信息 ***
表名::          mainMenu
表名宏定义::    conTBLNameMainMenu
表资源宏定义::  conResIDMainMenu
关键字::        mainMenuName
*/

// 定义表记录对应的结构
typedef struct
{
	char	mainMenuName[128+1];	// 主菜单名称
	char	mainMenuItemsList[1024+1];	// 主菜单项清单
	char	projectID[40+1];	// 项目编号
	int	useMenuItemButton;	// 是否使用命令按钮
	int	useServerMenu;	// 是否使用后台菜单
	char	remark[128+1];	// 128个字符的说明
	char	inputTeller[20+1];	// 记录插入数据库时，系统自动附加的操作员标识
	char	inputDate[8+1];	// 记录插入数据库时，系统自动附加的日期
	char	inputTime[6+1];	// 记录插入数据库时，系统自动附加的时间
	char	updateTeller[20+1];	// 记录修改时，系统自动附加的操作员标识
	char	updateDate[8+1];	// 记录修改时，系统自动附加的日期
	char	updateTime[6+1];	// 记录修改时，系统自动附加的时间
	char	iconFileName[40+1];	// 图标文件名
} TUnionMainMenu;
typedef TUnionMainMenu	*PUnionMainMenu;

