# 配置说明
# 第一个域: 如中括号括起来,是与数据库相关程序或库文件, 为菜单的提示信息
#         : 如小括号括起来,是与数据库无关程序或库文件, 为菜单的提示信息
#     当菜单提示信息为null时，则为空白行菜单
# 最后一个域为makefile文件名,支持多个，用,号分隔
[管理类程序]		commBins.mk
[工具类程序]		tools.mk
#[通讯类程序]		tcpipSvr.mk
[系统服务类程序]	sysSvr.mk
#[标准UI服务类程序]	serviceForUI.mk
#[标准APP服务类程序]	hsmTask-so.mk

[基础APP程序]		appTask.mk

[数据库测试]		testdb.2.0.mk
[查看动态库版本程序]	dlVersion.mk

[文件传送测试]		fileSender.mk

# 以下为与数据无关程序或库清单
#(查看动态库版本程序)	dlVersion.mk

