// Automatically generated codes
// Generated Date and Time 20100420151358
// Generated by ud090401

#ifndef _unionMngSvrDBDataSynJnl_
#define _unionMngSvrDBDataSynJnl_

#ifdef _unionMngSvrDBDataSynJnl_struct_20090421_
#include "unionMngSvrDBDataSynJnl_struct_20090421.h"
#else
#include "unionMngSvrDBDataSynJnl_struct_20090421.h"
#endif
//***** 以下定义函数声明 *****


/*
功能：
	结构的缺省赋值函数
输入参数:
	prec	记录指针
输出参数:
	无
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormDefaultValueOfMngSvrDBDataSynJnlRec(PUnionMngSvrDBDataSynJnl prec);


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormRecStrFromMngSvrDBDataSynJnlRec(PUnionMngSvrDBDataSynJnl prec,char *recStr,int sizeOfBuf);


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormPrimaryKeyRecStrFromMngSvrDBDataSynJnlRec(PUnionMngSvrDBDataSynJnl prec,char *recStr,int sizeOfBuf);


/*
功能：
	将记录字串转换为记录结构的关键字的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormPrimaryKeyOfMngSvrDBDataSynJnlRecFromRecStr(char *recStr,int lenOfRecStr,PUnionMngSvrDBDataSynJnl prec);


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormNonPrimaryKeyRecStrFromMngSvrDBDataSynJnlRec(PUnionMngSvrDBDataSynJnl prec,char *recStr,int sizeOfBuf);


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormMngSvrDBDataSynJnlRecFromRecStr(char *recStr,int lenOfRecStr,PUnionMngSvrDBDataSynJnl prec);


/*
功能：
	插入一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionInsertMngSvrDBDataSynJnlRec(PUnionMngSvrDBDataSynJnl prec);


/*
功能：
	删除一个记录
输入参数:
	date 插入记录的日期
	seqNo 流水号
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionDeleteMngSvrDBDataSynJnlRec(char *date,double seqNo);
/*
函数功能:
	修改指定的表域:
输入参数:
	date 插入记录的日期
	seqNo 流水号
	fldName 域名称
	fldValue 域值
	fldValueLen 域值长度
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateSpecFldOfMngSvrDBDataSynJnlRec(char *date,double seqNo,char *fldName,char *fldValue,int lenOfFldValue);
/*
函数功能:
	修改指定的表域:
输入参数:
	date 插入记录的日期
	seqNo 流水号
	fldName 域名称
	fldValue 域值
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateIntTypeSpecFldOfMngSvrDBDataSynJnlRec(char *date,double seqNo,char *fldName,int fldValue);


/*
功能：
	修改一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionUpdateMngSvrDBDataSynJnlRec(PUnionMngSvrDBDataSynJnl prec);


/*
功能：
	读取一个记录
输入参数:
	date 插入记录的日期
	seqNo 流水号
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadMngSvrDBDataSynJnlRec(char *date,double seqNo,PUnionMngSvrDBDataSynJnl prec);


/*
功能：
	读取一个记录
输入参数:
	date 插入记录的日期
	seqNo 流水号
	fldName		域名
	sizeOfBuf	域值缓冲大小
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadMngSvrDBDataSynJnlRecFld(char *date,double seqNo,char *fldName,char *fldValue,int sizeOfBuf);


/*
功能：
	读取一个记录
输入参数:
	date 插入记录的日期
	seqNo 流水号
	fldName		域名
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadMngSvrDBDataSynJnlRecIntTypeFld(char *date,double seqNo,char *fldName,int *fldValue);


/*
功能：
	根据条件，批量读取数据
输入参数:
	condition	条件字串
	maxRecNum		读取的最大记录数量
输出参数:
	recGrp		记录数组
返回值
	>=0		成功,读取的记录数量
	<0		失败,错误码
*/
int UnionBatchReadMngSvrDBDataSynJnlRec(char *condition,TUnionMngSvrDBDataSynJnl recGrp[],int maxRecNum);

//***** 函数声明结束 *****

#endif
