// Automatically generated codes
// Generated Date and Time 20090523221638
// Generated by ud090401

#ifndef _unionMngServiceOnline_
#define _unionMngServiceOnline_


// 定义表的域名常量
#define conMngServiceOnlineFldNameDirectionTag		"directionTag"
#define conMngServiceOnlineFldNameDate		"date"
#define conMngServiceOnlineFldNameTime		"time"
#define conMngServiceOnlineFldNameTellerNo		"tellerNo"
#define conMngServiceOnlineFldNameResID		"resID"
#define conMngServiceOnlineFldNameTableName		"tableName"
#define conMngServiceOnlineFldNameServiceID		"serviceID"
#define conMngServiceOnlineFldNameServiceName		"serviceName"
#define conMngServiceOnlineFldNameResponseCode		"responseCode"
#define conMngServiceOnlineFldNameClientIPAddr		"clientIPAddr"
#define conMngServiceOnlineFldNamePort		"port"
#define conMngServiceOnlineFldNameSsn		"ssn"
#define conMngServiceOnlineFldNamePid		"pid"
#define conMngServiceOnlineFldNameFileTransferred		"fileTransferred"
#define conMngServiceOnlineFldNameLenOfData		"lenOfData"
#define conMngServiceOnlineFldNameData		"data"
#define conMngServiceOnlineFldNameInputDate		"inputDate"
#define conMngServiceOnlineFldNameInputTime		"inputTime"

/*
*** 结构对应的表信息 ***
表名::          mngServiceOnline
表名宏定义::    conTBLNameMngServiceOnline
表资源宏定义::  conResIDMngServiceOnline
关键字::        date,time,clientIPAddr,port,ssn,pid,directionTag
*/

// 定义表记录对应的结构
typedef struct
{
	char	directionTag;	// 1位的请求标识,值固定为1
	char	date[8+1];	// 数据
	char	time[6+1];	// 数据
	char	tellerNo[40+1];	// 操作员代码
	int	resID;	// 资源ID号
	char	tableName[40+1];	// 表名称
	int	serviceID;	// 服务代码
	char	serviceName[40+1];	// 操作名称
	int	responseCode;	// 服务响应代码
	char	clientIPAddr[15+1];
	int	port;
	int	ssn;	// 服务流水号
	int	pid;	// 处理进程号
	int	fileTransferred;	// 传输了文件
	int	lenOfData;	// 数据正文长度
	char	data[8192*2+1];	// 数据正文
	char	inputDate[8+1];	// 记录插入数据库时，系统自动附加的日期
	char	inputTime[6+1];	// 记录插入数据库时，系统自动附加的时间
} TUnionMngServiceOnline;
typedef TUnionMngServiceOnline	*PUnionMngServiceOnline;

//***** 以下定义函数声明 *****


/*
功能：
	结构的缺省赋值函数
输入参数:
	prec	记录指针
输出参数:
	无
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormDefaultValueOfMngServiceOnlineRec(PUnionMngServiceOnline prec);


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormRecStrFromMngServiceOnlineRec(PUnionMngServiceOnline prec,char *recStr,int sizeOfBuf);


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec(PUnionMngServiceOnline prec,char *recStr,int sizeOfBuf);


/*
功能：
	将记录字串转换为记录结构的关键字的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr(char *recStr,int lenOfRecStr,PUnionMngServiceOnline prec);


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec(PUnionMngServiceOnline prec,char *recStr,int sizeOfBuf);


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormMngServiceOnlineRecFromRecStr(char *recStr,int lenOfRecStr,PUnionMngServiceOnline prec);


/*
功能：
	插入一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionInsertMngServiceOnlineRec(PUnionMngServiceOnline prec);


/*
功能：
	删除一个记录
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionDeleteMngServiceOnlineRec(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag);
/*
函数功能:
	修改指定的表域:
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
	fldName 域名称
	fldValue 域值
	fldValueLen 域值长度
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateSpecFldOfMngServiceOnlineRec(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,char *fldName,char *fldValue,int lenOfFldValue);
/*
函数功能:
	修改指定的表域:
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
	fldName 域名称
	fldValue 域值
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,char *fldName,int fldValue);


/*
功能：
	修改一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionUpdateMngServiceOnlineRec(PUnionMngServiceOnline prec);


/*
功能：
	读取一个记录
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadMngServiceOnlineRec(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,PUnionMngServiceOnline prec);


/*
功能：
	读取一个记录
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
	fldName		域名
	sizeOfBuf	域值缓冲大小
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadMngServiceOnlineRecFld(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,char *fldName,char *fldValue,int sizeOfBuf);


/*
功能：
	读取一个记录
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
	fldName		域名
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadMngServiceOnlineRecIntTypeFld(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,char *fldName,int *fldValue);


/*
功能：
	根据条件，批量读取数据
输入参数:
	condition	条件字串
	maxRecNum		读取的最大记录数量
输出参数:
	recGrp		记录数组
返回值
	>=0		成功,读取的记录数量
	<0		失败,错误码
*/
int UnionBatchReadMngServiceOnlineRec(char *condition,TUnionMngServiceOnline recGrp[],int maxRecNum);

//***** 函数声明结束 *****

#endif
