// Automatically generated codes
// Generated Date and Time 20100602200439
// Generated by ud090401

#ifndef _unionComplexField_struct_20090421_
#define _unionComplexField_struct_20090421_
#endif


// 定义表的域名常量
#define conComplexFieldFldNameMainMenuName		"mainMenuName"
#define conComplexFieldFldNameComplexFieldID		"complexFieldID"
#define conComplexFieldFldNameFieldSeparator		"fieldSeparator"
#define conComplexFieldFldNameSpecialFieldSeparators		"specialFieldSeparators"
#define conComplexFieldFldNameSpecialLineTag		"specialLineTag"
#define conComplexFieldFldNameLineSeparator		"lineSeparator"
#define conComplexFieldFldNameMaxNumOfLine		"maxNumOfLine"
#define conComplexFieldFldNameMinNumOfLine		"minNumOfLine"
#define conComplexFieldFldNameTableFldList		"tableFldList"
#define conComplexFieldFldNameRemark		"remark"
#define conComplexFieldFldNameInputTeller		"inputTeller"
#define conComplexFieldFldNameInputDate		"inputDate"
#define conComplexFieldFldNameInputTime		"inputTime"
#define conComplexFieldFldNameUpdateTeller		"updateTeller"
#define conComplexFieldFldNameUpdateDate		"updateDate"
#define conComplexFieldFldNameUpdateTime		"updateTime"

/*
*** 结构对应的表信息 ***
表名::          complexField
表名宏定义::    conTBLNameComplexField
表资源宏定义::  conResIDComplexField
关键字::        mainMenuName,complexFieldID
*/

// 定义表记录对应的结构
typedef struct
{
	char	mainMenuName[128+1];	// 主菜单名称
	char	complexFieldID[40+1];	// 复合域标识
	char	fieldSeparator[20+1];	// 域分隔符
	char	specialFieldSeparators[128+1];	// 指定域的分隔符
	char	specialLineTag[512+1];	// 指定行作的标签
	char	lineSeparator[20+1];	// 行分隔符
	int	maxNumOfLine;	// 最大行数
	int	minNumOfLine;	// 最小行数
	char	tableFldList[512+1];	// 表域清单
	char	remark[128+1];	// 128个字符的说明
	char	inputTeller[20+1];	// 记录插入数据库时，系统自动附加的操作员标识
	char	inputDate[8+1];	// 记录插入数据库时，系统自动附加的日期
	char	inputTime[6+1];	// 记录插入数据库时，系统自动附加的时间
	char	updateTeller[20+1];	// 记录修改时，系统自动附加的操作员标识
	char	updateDate[8+1];	// 记录修改时，系统自动附加的日期
	char	updateTime[6+1];	// 记录修改时，系统自动附加的时间
} TUnionComplexField;
typedef TUnionComplexField	*PUnionComplexField;

