// Automatically generated codes
// Generated Date and Time 20091109160749
// Generated by ud090401

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "UnionLog.h"
#include "UnionStr.h"
#include "unionErrCode.h"
#include "unionDataTBLList.h"

#include "unionAutoFldDef.h"


/*
功能：
	结构的缺省赋值函数
输入参数:
	prec	记录指针
输出参数:
	无
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormDefaultValueOfAutoFldDefRec(PUnionAutoFldDef prec)
{
	int	ret;

	if (prec == NULL)
	{
		UnionUserErrLog("in UnionFormDefaultValueOfAutoFldDefRec:: prec is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	memset(prec,0,sizeof(*prec));
	return(0);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormRecStrFromAutoFldDefRec(PUnionAutoFldDef prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormRecStrFromAutoFldDefRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	if ((ret = UnionFormPrimaryKeyRecStrFromAutoFldDefRec(prec,recStr,sizeOfBuf)) < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromAutoFldDefRec:: UnionFormPrimaryKeyRecStrFromAutoFldDefRec!\n");
		return(ret);
	}
	offset = ret;
	if ((ret = UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec(prec,recStr+offset,sizeOfBuf-offset)) < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromAutoFldDefRec:: UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec!\n");
		return(ret);
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormPrimaryKeyRecStrFromAutoFldDefRec(PUnionAutoFldDef prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromAutoFldDefRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameDesResName,prec->desResName,strlen(prec->desResName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [desResName] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameDesFldName,prec->desFldName,strlen(prec->desFldName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [desFldName] error!\n");
		return(ret);
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec(PUnionAutoFldDef prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameDesConFldList,prec->desConFldList,strlen(prec->desConFldList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [desConFldList] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameOriResName,prec->oriResName,strlen(prec->oriResName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [oriResName] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameOriFldName,prec->oriFldName,strlen(prec->oriFldName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [oriFldName] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameOriConFldList,prec->oriConFldList,strlen(prec->oriConFldList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [oriConFldList] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameRemark,prec->remark,strlen(prec->remark),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [remark] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameInputTeller,prec->inputTeller,strlen(prec->inputTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [inputTeller] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameInputDate,prec->inputDate,strlen(prec->inputDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [inputDate] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameInputTime,prec->inputTime,strlen(prec->inputTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [inputTime] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameUpdateTeller,prec->updateTeller,strlen(prec->updateTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [updateTeller] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameUpdateDate,prec->updateDate,strlen(prec->updateDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [updateDate] error!\n");
		return(ret);
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conAutoFldDefFldNameUpdateTime,prec->updateTime,strlen(prec->updateTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec:: UnionPutRecFldIntoRecStr [updateTime] error!\n");
		return(ret);
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录字串转换为记录结构的关键字的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormPrimaryKeyOfAutoFldDefRecFromRecStr(char *recStr,int lenOfRecStr,PUnionAutoFldDef prec)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormPrimaryKeyOfAutoFldDefRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfAutoFldDefRec(prec);
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameDesResName,prec->desResName,sizeof(prec->desResName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [desResName] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameDesFldName,prec->desFldName,sizeof(prec->desFldName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [desFldName] error!\n");
			return(ret);
		}
	}
	return(0);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormAutoFldDefRecFromRecStr(char *recStr,int lenOfRecStr,PUnionAutoFldDef prec)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfAutoFldDefRec(prec);
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameDesResName,prec->desResName,sizeof(prec->desResName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [desResName] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameDesFldName,prec->desFldName,sizeof(prec->desFldName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [desFldName] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameDesConFldList,prec->desConFldList,sizeof(prec->desConFldList));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [desConFldList] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameOriResName,prec->oriResName,sizeof(prec->oriResName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [oriResName] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameOriFldName,prec->oriFldName,sizeof(prec->oriFldName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [oriFldName] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameOriConFldList,prec->oriConFldList,sizeof(prec->oriConFldList));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [oriConFldList] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameRemark,prec->remark,sizeof(prec->remark));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [remark] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameInputTeller,prec->inputTeller,sizeof(prec->inputTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTeller] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameInputDate,prec->inputDate,sizeof(prec->inputDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputDate] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameInputTime,prec->inputTime,sizeof(prec->inputTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTime] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameUpdateTeller,prec->updateTeller,sizeof(prec->updateTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTeller] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameUpdateDate,prec->updateDate,sizeof(prec->updateDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateDate] error!\n");
			return(ret);
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conAutoFldDefFldNameUpdateTime,prec->updateTime,sizeof(prec->updateTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormAutoFldDefRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTime] error!\n");
			return(ret);
		}
	}
	return(0);
}


/*
功能：
	插入一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionInsertAutoFldDefRec(PUnionAutoFldDef prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormRecStrFromAutoFldDefRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertAutoFldDefRec:: UnionFormRecStrFromAutoFldDefRec!\n");
		return(lenOfRecStr);
	}

	//赋加自动插入域
	if ((lenOfRecStr = UnionAutoAppendDBRecInputAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertAutoFldDefRec:: UnionAutoAppendDBRecInputAttr!\n");
		return(lenOfRecStr);
	}

	//插入记录
	if ((ret = UnionInsertObjectRecord(conTBLNameAutoFldDef,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionInsertAutoFldDefRec:: UnionInsertObjectRecord!\n");
		return(ret);
	}

	return(ret);
}


/*
功能：
	删除一个记录
输入参数:
	desResName 目标表名
	desFldName 目标字段名
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionDeleteAutoFldDefRec(char *desResName,char *desFldName)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("desResName",desResName,strlen(desResName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteAutoFldDefRec:: UnionPutRecFldIntoRecStr [desResName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("desFldName",desFldName,strlen(desFldName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteAutoFldDefRec:: UnionPutRecFldIntoRecStr [desFldName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	//删除记录
	if ((ret = UnionDeleteUniqueObjectRecord(conTBLNameAutoFldDef,recStr)) < 0)
	{
		UnionUserErrLog("in UnionDeleteAutoFldDefRec:: UnionDeleteUniqueObjectRecord!\n");
		return(ret);
	}

	return(ret);
}


/*
功能：
	修改一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionUpdateAutoFldDefRec(PUnionAutoFldDef prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	primaryKey[1024+1];

	//从记录拼关键字
	memset(primaryKey,0,sizeof(primaryKey));
	if ((ret = UnionFormPrimaryKeyRecStrFromAutoFldDefRec(prec,primaryKey,sizeof(primaryKey))) < 0)
	{
		UnionUserErrLog("in UnionUpdateAutoFldDefRec:: UnionFormPrimaryKeyRecStrFromAutoFldDefRec!\n");
		return(ret);
	}

	//从记录接记录串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateAutoFldDefRec:: UnionFormNonPrimaryKeyRecStrFromAutoFldDefRec!\n");
		return(lenOfRecStr);
	}

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateAutoFldDefRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(lenOfRecStr);
	}

	//修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameAutoFldDef,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateAutoFldDefRec:: UnionUpdateUniqueObjectRecord!\n");
		return(ret);
	}

	return(ret);
}
/*
函数功能:
	修改指定的表域:
输入参数:
	desResName 目标表名
	desFldName 目标字段名
	fldName 域名称
	fldValue 域值
	fldValueLen 域值长度
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateSpecFldOfAutoFldDefRec(char *desResName,char *desFldName,char *fldName,char *fldValue,int lenOfFldValue)
{
	int	ret;
	char	recStr[8192*2+1];
	char	primaryKey[1024+1];
	int	lenOfRecStr = 0;

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("desResName",desResName,strlen(desResName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfAutoFldDefRec:: UnionPutRecFldIntoRecStr [desResName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("desFldName",desFldName,strlen(desFldName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfAutoFldDefRec:: UnionPutRecFldIntoRecStr [desFldName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	strcpy(primaryKey,recStr);

	// 组记录
	memset(recStr,0,sizeof(recStr));
	lenOfRecStr = 0;
	if ((ret = UnionPutRecFldIntoRecStr(fldName,fldValue,lenOfFldValue,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfAutoFldDefRec:: UnionPutRecFldIntoRecStr [%s] failure!\n",fldName);
		return(ret);
	}
	lenOfRecStr += ret;

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfAutoFldDefRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(lenOfRecStr);
	}

	// 修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameAutoFldDef,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfAutoFldDefRec:: UnionUpdateUniqueObjectRecord!\n");
		return(ret);
	}

	return(ret);
}

/*
函数功能:
	修改指定的表域:
输入参数:
	desResName 目标表名
	desFldName 目标字段名
	fldName 域名称
	fldValue 域值
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateIntTypeSpecFldOfAutoFldDefRec(char *desResName,char *desFldName,char *fldName,int fldValue)
{
	int	ret;
	char	recStr[8192*2+1];
	char	primaryKey[1024+1];
	int	lenOfRecStr = 0;

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("desResName",desResName,strlen(desResName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfAutoFldDefRec:: UnionPutRecFldIntoRecStr [desResName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("desFldName",desFldName,strlen(desFldName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfAutoFldDefRec:: UnionPutRecFldIntoRecStr [desFldName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	strcpy(primaryKey,recStr);

	// 组记录
	memset(recStr,0,sizeof(recStr));
	lenOfRecStr = 0;
	if ((ret = UnionPutIntTypeRecFldIntoRecStr(fldName,fldValue,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfAutoFldDefRec:: UnionPutIntTypeRecFldIntoRecStr [%s] failure!\n",fldName);
		return(ret);
	}
	lenOfRecStr += ret;

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfAutoFldDefRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(lenOfRecStr);
	}

	// 修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameAutoFldDef,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfAutoFldDefRec:: UnionUpdateUniqueObjectRecord!\n");
		return(ret);
	}

	return(ret);
}



/*
功能：
	读取一个记录
输入参数:
	desResName 目标表名
	desFldName 目标字段名
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadAutoFldDefRec(char *desResName,char *desFldName,PUnionAutoFldDef prec)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("desResName",desResName,strlen(desResName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRec:: UnionPutRecFldIntoRecStr [desResName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("desFldName",desFldName,strlen(desFldName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRec:: UnionPutRecFldIntoRecStr [desFldName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadAutoFldDefRec:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameAutoFldDef,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRec:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(lenOfRecStr);
	}

	//从记录串拼装结构
	if ((ret = UnionFormAutoFldDefRecFromRecStr(recStr,lenOfRecStr,prec)) < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRec:: UnionFormAutoFldDefRecFromRecStr!\n");
		return(ret);
	}

	return(sizeof(*prec));
}


/*
功能：
	读取一个记录
输入参数:
	desResName 目标表名
	desFldName 目标字段名
	fldName		域名
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadAutoFldDefRecIntTypeFld(char *desResName,char *desFldName,char *fldName,int *fldValue)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("desResName",desResName,strlen(desResName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecIntTypeFld:: UnionPutRecFldIntoRecStr [desResName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("desFldName",desFldName,strlen(desFldName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecIntTypeFld:: UnionPutRecFldIntoRecStr [desFldName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecIntTypeFld:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameAutoFldDef,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecIntTypeFld:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(lenOfRecStr);
	}

	//读指定域
	if ((ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue)) < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecIntTypeFld:: UnionReadIntTypeRecFldFromRecStr!\n");
		return(ret);
	}

	return(ret);
}


/*
功能：
	读取一个记录
输入参数:
	desResName 目标表名
	desFldName 目标字段名
	fldName		域名
	sizeOfBuf	域值缓冲大小
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadAutoFldDefRecFld(char *desResName,char *desFldName,char *fldName,char *fldValue,int sizeOfBuf)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("desResName",desResName,strlen(desResName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecFld:: UnionPutRecFldIntoRecStr [desResName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("desFldName",desFldName,strlen(desFldName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecFld:: UnionPutRecFldIntoRecStr [desFldName] failure!\n");
		return(ret);
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecFld:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameAutoFldDef,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecFld:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(lenOfRecStr);
	}

	//读指定域
	if ((ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue,sizeOfBuf)) < 0)
	{
		UnionUserErrLog("in UnionReadAutoFldDefRecFld:: UnionReadRecFldFromRecStr!\n");
		return(ret);
	}

	return(ret);
}


/*
功能：
	根据条件，批量读取数据
输入参数:
	condition	条件字串
	maxRecNum		读取的最大记录数量
输出参数:
	recGrp		记录数组
返回值
	>=0		成功,读取的记录数量
	<0		失败,错误码
*/
int UnionBatchReadAutoFldDefRec(char *condition,TUnionAutoFldDef recGrp[],int maxRecNum)
{
	int	ret;
	char	fileName[512+1];
	int	recNum = 0;
	FILE	*recFileFp = NULL;
	char	recStr[8192*2+1];
	int	lenOfRecStr;
	char	tableName[128+1];
	TUnionAutoFldDef	rec;

	memset(fileName,0,sizeof(fileName));
	sprintf(fileName,"%s/pid-%d.tmp",getenv("UNIONTEMP"),getpid());

// 读所有记录
	if ((ret = UnionBatchSelectObjectRecord(conTBLNameAutoFldDef,condition,fileName)) < 0)
	{
		UnionUserErrLog("in UnionBatchReadAutoFldDefRec:: UnionBatchSelectObjectRecord from [%s] on [%s]!\n",conTBLNameAutoFldDef,condition);
		return(ret);
	}
	// 打开文件
	if ((recFileFp = fopen(fileName,"r")) == NULL)
	{
		UnionUserErrLog("in UnionBatchReadAutoFldDefRec:: fopen [%s]\n",fileName);
		goto errExit;
	}
	while (!feof(recFileFp))
	{
		if (recNum >= maxRecNum)
		{
			UnionLog("in UnionBatchReadAutoFldDefRec:: still exists records satisfy the condition [%s]!\n",condition);
			ret = recNum;
			goto errExit;
		}
		memset(recStr,0,sizeof(recStr));
		if ((lenOfRecStr = UnionReadOneDataLineFromTxtFile(recFileFp,recStr,sizeof(recStr))) <= 0)
			continue;
		memset(&rec,0,sizeof(rec));
		if ((ret = UnionFormAutoFldDefRecFromRecStr(recStr,lenOfRecStr,&rec)) < 0)
		{
			UnionUserErrLog("in UnionBatchReadAutoFldDefRec:: UnionFormAutoFldDefRecFromRecStr from [%04d] [%s]\n",lenOfRecStr,recStr);
			goto errExit;
		}
		memcpy(&(recGrp[recNum]),&rec,sizeof(rec));
		recNum++;
	}
	ret = recNum;
errExit:
	fclose(recFileFp);
	UnionDeleteFile(fileName);
	return(ret);

}
