// Automatically generated codes
// Generated Date and Time 20100324162542
// Generated by ud090401

#ifndef _unionViewList_struct_20090421_
#define _unionViewList_struct_20090421_
#endif

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>

#ifndef _UnionLogMDL_3_x_ 
#define _UnionLogMDL_3_x_
#endif

#include "UnionLog.h"
#include "UnionStr.h"
#include "unionErrCode.h"
#include "unionComplexDBRecord.h"
#include "unionDataTBLList.h"

#include "unionViewList.h"
#include "unionRecFile.h"
#include "simuMngSvrLocally.h"


/*
功能：
	结构的缺省赋值函数
输入参数:
	prec	记录指针
输出参数:
	无
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormDefaultValueOfViewListRec(PUnionViewList prec)
{
	if (prec == NULL)
	{
		UnionUserErrLog("in UnionFormDefaultValueOfViewListRec:: prec is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	memset(prec,0,sizeof(*prec));
	prec->maxNumOfRecPerPage = 32;
	prec->useSeparateTBL = 1;
	return(0);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormRecStrFromViewListRec(PUnionViewList prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormRecStrFromViewListRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	if ((ret = UnionFormPrimaryKeyRecStrFromViewListRec(prec,recStr,sizeOfBuf)) < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromViewListRec:: UnionFormPrimaryKeyRecStrFromViewListRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset = ret;
	if ((ret = UnionFormNonPrimaryKeyRecStrFromViewListRec(prec,recStr+offset,sizeOfBuf-offset)) < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromViewListRec:: UnionFormNonPrimaryKeyRecStrFromViewListRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormPrimaryKeyRecStrFromViewListRec(PUnionViewList prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromViewListRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameMainMenuName,prec->mainMenuName,strlen(prec->mainMenuName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [mainMenuName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameID,prec->ID,strlen(prec->ID),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [ID] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormNonPrimaryKeyRecStrFromViewListRec(PUnionViewList prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameViewAlais,prec->viewAlais,strlen(prec->viewAlais),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [viewAlais] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameTableName,prec->tableName,strlen(prec->tableName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [tableName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conViewListFldNameResID,prec->resID,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutIntTypeRecFldIntoRecStr [resID] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conViewListFldNameTableTypeID,prec->tableTypeID,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutIntTypeRecFldIntoRecStr [tableTypeID] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNamePrimaryKey,prec->primaryKey,strlen(prec->primaryKey),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [primaryKey] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameFieldList,prec->fieldList,strlen(prec->fieldList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [fieldList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameFieldAlaisList,prec->fieldAlaisList,strlen(prec->fieldAlaisList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [fieldAlaisList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameFieldDisplayList,prec->fieldDisplayList,strlen(prec->fieldDisplayList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [fieldDisplayList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameFieldConstraintDef,prec->fieldConstraintDef,strlen(prec->fieldConstraintDef),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [fieldConstraintDef] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameViewCondition,prec->viewCondition,strlen(prec->viewCondition),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [viewCondition] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameViewQueryDef,prec->viewQueryDef,strlen(prec->viewQueryDef),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [viewQueryDef] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameFormIconFileName,prec->formIconFileName,strlen(prec->formIconFileName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [formIconFileName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameFormPopMenuDefFileName,prec->formPopMenuDefFileName,strlen(prec->formPopMenuDefFileName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [formPopMenuDefFileName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameRecIconFileName,prec->recIconFileName,strlen(prec->recIconFileName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [recIconFileName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameRecPopMenuDefFileName,prec->recPopMenuDefFileName,strlen(prec->recPopMenuDefFileName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [recPopMenuDefFileName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameRecDoubleClickMenuFileName,prec->recDoubleClickMenuFileName,strlen(prec->recDoubleClickMenuFileName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [recDoubleClickMenuFileName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conViewListFldNameMaxNumOfRecPerPage,prec->maxNumOfRecPerPage,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutIntTypeRecFldIntoRecStr [maxNumOfRecPerPage] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conViewListFldNameUseSeparateTBL,prec->useSeparateTBL,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutIntTypeRecFldIntoRecStr [useSeparateTBL] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameLoopList,prec->loopList,strlen(prec->loopList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [loopList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameViewLevel,prec->viewLevel,strlen(prec->viewLevel),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [viewLevel] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameEditLevel,prec->editLevel,strlen(prec->editLevel),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [editLevel] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameRemark,prec->remark,strlen(prec->remark),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [remark] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameInputTeller,prec->inputTeller,strlen(prec->inputTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [inputTeller] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameInputDate,prec->inputDate,strlen(prec->inputDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [inputDate] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameInputTime,prec->inputTime,strlen(prec->inputTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [inputTime] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameUpdateTeller,prec->updateTeller,strlen(prec->updateTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [updateTeller] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameUpdateDate,prec->updateDate,strlen(prec->updateDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [updateDate] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conViewListFldNameUpdateTime,prec->updateTime,strlen(prec->updateTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromViewListRec:: UnionPutRecFldIntoRecStr [updateTime] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录字串转换为记录结构的关键字的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormPrimaryKeyOfViewListRecFromRecStr(char *recStr,int lenOfRecStr,PUnionViewList prec)
{
	int	ret;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormPrimaryKeyOfViewListRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfViewListRec(prec);
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameMainMenuName,prec->mainMenuName,sizeof(prec->mainMenuName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [mainMenuName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameID,prec->ID,sizeof(prec->ID));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [ID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	return(0);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormViewListRecFromRecStr(char *recStr,int lenOfRecStr,PUnionViewList prec)
{
	int	ret;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormViewListRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfViewListRec(prec);
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameMainMenuName,prec->mainMenuName,sizeof(prec->mainMenuName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [mainMenuName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameID,prec->ID,sizeof(prec->ID));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [ID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameViewAlais,prec->viewAlais,sizeof(prec->viewAlais));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [viewAlais] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameTableName,prec->tableName,sizeof(prec->tableName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [tableName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameResID,&(prec->resID));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [resID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameTableTypeID,&(prec->tableTypeID));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [tableTypeID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNamePrimaryKey,prec->primaryKey,sizeof(prec->primaryKey));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [primaryKey] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameFieldList,prec->fieldList,sizeof(prec->fieldList));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [fieldList] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameFieldAlaisList,prec->fieldAlaisList,sizeof(prec->fieldAlaisList));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [fieldAlaisList] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameFieldDisplayList,prec->fieldDisplayList,sizeof(prec->fieldDisplayList));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [fieldDisplayList] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameFieldConstraintDef,prec->fieldConstraintDef,sizeof(prec->fieldConstraintDef));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [fieldConstraintDef] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameViewCondition,prec->viewCondition,sizeof(prec->viewCondition));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [viewCondition] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameViewQueryDef,prec->viewQueryDef,sizeof(prec->viewQueryDef));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [viewQueryDef] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameFormIconFileName,prec->formIconFileName,sizeof(prec->formIconFileName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [formIconFileName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameFormPopMenuDefFileName,prec->formPopMenuDefFileName,sizeof(prec->formPopMenuDefFileName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [formPopMenuDefFileName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameRecIconFileName,prec->recIconFileName,sizeof(prec->recIconFileName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [recIconFileName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameRecPopMenuDefFileName,prec->recPopMenuDefFileName,sizeof(prec->recPopMenuDefFileName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [recPopMenuDefFileName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameRecDoubleClickMenuFileName,prec->recDoubleClickMenuFileName,sizeof(prec->recDoubleClickMenuFileName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [recDoubleClickMenuFileName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameMaxNumOfRecPerPage,&(prec->maxNumOfRecPerPage));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [maxNumOfRecPerPage] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameUseSeparateTBL,&(prec->useSeparateTBL));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [useSeparateTBL] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameLoopList,prec->loopList,sizeof(prec->loopList));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [loopList] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameViewLevel,prec->viewLevel,sizeof(prec->viewLevel));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [viewLevel] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameEditLevel,prec->editLevel,sizeof(prec->editLevel));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [editLevel] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameRemark,prec->remark,sizeof(prec->remark));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [remark] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameInputTeller,prec->inputTeller,sizeof(prec->inputTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTeller] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameInputDate,prec->inputDate,sizeof(prec->inputDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputDate] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameInputTime,prec->inputTime,sizeof(prec->inputTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTime] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameUpdateTeller,prec->updateTeller,sizeof(prec->updateTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTeller] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameUpdateDate,prec->updateDate,sizeof(prec->updateDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateDate] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conViewListFldNameUpdateTime,prec->updateTime,sizeof(prec->updateTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormViewListRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTime] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	return(0);
}


/*
功能：
	插入一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionInsertViewListRec(PUnionViewList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormRecStrFromViewListRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertViewListRec:: UnionFormRecStrFromViewListRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//赋加自动插入域
	if ((lenOfRecStr = UnionAutoAppendDBRecInputAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertViewListRec:: UnionAutoAppendDBRecInputAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//插入记录
	if ((ret = UnionInsertObjectRecord(conTBLNameViewList,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionInsertViewListRec:: UnionInsertObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	删除一个记录
输入参数:
	ID 用户定义的，用于唯一识别一条记录的名称
	mainMenuName 主菜单名称
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionDeleteViewListRec(char *ID,char *mainMenuName)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("ID",ID,strlen(ID),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteViewListRec:: UnionPutRecFldIntoRecStr [ID] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteViewListRec:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	//删除记录
	if ((ret = UnionDeleteUniqueObjectRecord(conTBLNameViewList,recStr)) < 0)
	{
		UnionUserErrLog("in UnionDeleteViewListRec:: UnionDeleteUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	修改一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionUpdateViewListRec(PUnionViewList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	primaryKey[1024+1];

	//从记录拼关键字
	memset(primaryKey,0,sizeof(primaryKey));
	if ((ret = UnionFormPrimaryKeyRecStrFromViewListRec(prec,primaryKey,sizeof(primaryKey))) < 0)
	{
		UnionUserErrLog("in UnionUpdateViewListRec:: UnionFormPrimaryKeyRecStrFromViewListRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	//从记录接记录串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormNonPrimaryKeyRecStrFromViewListRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateViewListRec:: UnionFormNonPrimaryKeyRecStrFromViewListRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateViewListRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameViewList,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateViewListRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}
/*
函数功能:
	修改指定的表域:
输入参数:
	ID 用户定义的，用于唯一识别一条记录的名称
	mainMenuName 主菜单名称
	fldName 域名称
	fldValue 域值
	fldValueLen 域值长度
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateSpecFldOfViewListRec(char *ID,char *mainMenuName,char *fldName,char *fldValue,int lenOfFldValue)
{
	int	ret;
	char	recStr[8192*2+1];
	char	primaryKey[1024+1];
	int	lenOfRecStr = 0;

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("ID",ID,strlen(ID),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfViewListRec:: UnionPutRecFldIntoRecStr [ID] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfViewListRec:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	strcpy(primaryKey,recStr);

	// 组记录
	memset(recStr,0,sizeof(recStr));
	lenOfRecStr = 0;
	if ((ret = UnionPutRecFldIntoRecStr(fldName,fldValue,lenOfFldValue,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfViewListRec:: UnionPutRecFldIntoRecStr [%s] failure!\n",fldName);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfViewListRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	// 修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameViewList,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfViewListRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}

/*
函数功能:
	修改指定的表域:
输入参数:
	ID 用户定义的，用于唯一识别一条记录的名称
	mainMenuName 主菜单名称
	fldName 域名称
	fldValue 域值
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateIntTypeSpecFldOfViewListRec(char *ID,char *mainMenuName,char *fldName,int fldValue)
{
	int	ret;
	char	recStr[8192*2+1];
	char	primaryKey[1024+1];
	int	lenOfRecStr = 0;

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("ID",ID,strlen(ID),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfViewListRec:: UnionPutRecFldIntoRecStr [ID] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfViewListRec:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	strcpy(primaryKey,recStr);

	// 组记录
	memset(recStr,0,sizeof(recStr));
	lenOfRecStr = 0;
	if ((ret = UnionPutIntTypeRecFldIntoRecStr(fldName,fldValue,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfViewListRec:: UnionPutIntTypeRecFldIntoRecStr [%s] failure!\n",fldName);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfViewListRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	// 修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameViewList,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfViewListRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}



/*
功能：
	读取一个记录
输入参数:
	ID 用户定义的，用于唯一识别一条记录的名称
	mainMenuName 主菜单名称
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadViewListRec(char *ID,char *mainMenuName,PUnionViewList prec)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("ID",ID,strlen(ID),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadViewListRec:: UnionPutRecFldIntoRecStr [ID] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadViewListRec:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadViewListRec:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameViewList,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadViewListRec:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//从记录串拼装结构
	if ((ret = UnionFormViewListRecFromRecStr(recStr,lenOfRecStr,prec)) < 0)
	{
		UnionUserErrLog("in UnionReadViewListRec:: UnionFormViewListRecFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(sizeof(*prec));
}


/*
功能：
	读取一个记录
输入参数:
	ID 用户定义的，用于唯一识别一条记录的名称
	mainMenuName 主菜单名称
	fldName		域名
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadViewListRecIntTypeFld(char *ID,char *mainMenuName,char *fldName,int *fldValue)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("ID",ID,strlen(ID),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadViewListRecIntTypeFld:: UnionPutRecFldIntoRecStr [ID] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadViewListRecIntTypeFld:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadViewListRecIntTypeFld:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameViewList,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadViewListRecIntTypeFld:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//读指定域
	if ((ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue)) < 0)
	{
		UnionUserErrLog("in UnionReadViewListRecIntTypeFld:: UnionReadIntTypeRecFldFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	读取一个记录
输入参数:
	ID 用户定义的，用于唯一识别一条记录的名称
	mainMenuName 主菜单名称
	fldName		域名
	sizeOfBuf	域值缓冲大小
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadViewListRecFld(char *ID,char *mainMenuName,char *fldName,char *fldValue,int sizeOfBuf)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("ID",ID,strlen(ID),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadViewListRecFld:: UnionPutRecFldIntoRecStr [ID] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadViewListRecFld:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadViewListRecFld:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameViewList,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadViewListRecFld:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//读指定域
	if ((ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue,sizeOfBuf)) < 0)
	{
		UnionUserErrLog("in UnionReadViewListRecFld:: UnionReadRecFldFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	根据条件，批量读取数据
输入参数:
	condition	条件字串
	maxRecNum		读取的最大记录数量
输出参数:
	recGrp		记录数组
返回值
	>=0		成功,读取的记录数量
	<0		失败,错误码
*/
int UnionBatchReadViewListRec(char *condition,TUnionViewList recGrp[],int maxRecNum)
{
	int	ret;
	char	fileName[512+1];
	int	recNum = 0;
	FILE	*recFileFp = NULL;
	char	recStr[8192*2+1];
	int	lenOfRecStr;
	TUnionViewList	rec;

	memset(fileName,0,sizeof(fileName));
	sprintf(fileName,"%s/pid-%d.tmp",getenv("UNIONTEMP"),getpid());

// 读所有记录
	if ((ret = UnionBatchSelectObjectRecord(conTBLNameViewList,condition,fileName)) < 0)
	{
		UnionUserErrLog("in UnionBatchReadViewListRec:: UnionBatchSelectObjectRecord from [%s] on [%s]!\n",conTBLNameViewList,condition);
		return(ret);
	}
	// 打开文件
	if ((recFileFp = fopen(fileName,"r")) == NULL)
	{
		UnionUserErrLog("in UnionBatchReadViewListRec:: fopen [%s]\n",fileName);
		goto errExit;
	}
	while (!feof(recFileFp))
	{
		if (recNum >= maxRecNum)
		{
			UnionLog("in UnionBatchReadViewListRec:: still exists records satisfy the condition [%s]!\n",condition);
			ret = recNum;
			goto errExit;
		}
		memset(recStr,0,sizeof(recStr));
		if ((lenOfRecStr = UnionReadOneDataLineFromTxtFile(recFileFp,recStr,sizeof(recStr))) <= 0)
			continue;
		memset(&rec,0,sizeof(rec));
		if ((ret = UnionFormViewListRecFromRecStr(recStr,lenOfRecStr,&rec)) < 0)
		{
			UnionUserErrLog("in UnionBatchReadViewListRec:: UnionFormViewListRecFromRecStr from [%04d] [%s]\n",lenOfRecStr,recStr);
			goto errExit;
		}
		memcpy(&(recGrp[recNum]),&rec,sizeof(rec));
		recNum++;
	}
	ret = recNum;
errExit:
	fclose(recFileFp);
	UnionDeleteFile(fileName);
	return(ret);

}
