// Automatically generated codes
// Generated Date and Time 20090502150618
// Generated by ud090401

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "UnionLog.h"
#include "UnionStr.h"
#include "unionErrCode.h"
#include "unionDataTBLList.h"

#include "unionOperationList.h"
#include "unionComplexDBRecord.h"


/*
功能：
	结构的缺省赋值函数
输入参数:
	prec	记录指针
输出参数:
	无
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormDefaultValueOfOperationListRec(PUnionOperationList prec)
{
	int	ret;

	if (prec == NULL)
	{
		UnionUserErrLog("in UnionFormDefaultValueOfOperationListRec:: prec is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	memset(prec,0,sizeof(*prec));
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormRecStrFromOperationListRec(PUnionOperationList prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameID,prec->ID,strlen(prec->ID),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [ID] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameMacroName,prec->macroName,strlen(prec->macroName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [macroName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameMacroValue,prec->macroValue,strlen(prec->macroValue),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [macroValue] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameRemark,prec->remark,strlen(prec->remark),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [remark] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameInputTeller,prec->inputTeller,strlen(prec->inputTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [inputTeller] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameInputDate,prec->inputDate,strlen(prec->inputDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [inputDate] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameInputTime,prec->inputTime,strlen(prec->inputTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [inputTime] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameUpdateTeller,prec->updateTeller,strlen(prec->updateTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [updateTeller] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameUpdateDate,prec->updateDate,strlen(prec->updateDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [updateDate] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conOperationListFldNameUpdateTime,prec->updateTime,strlen(prec->updateTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromOperationListRec:: UnionPutRecFldIntoRecStr [updateTime] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormOperationListRecFromRecStr(char *recStr,int lenOfRecStr,PUnionOperationList prec)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfOperationListRec(prec);
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameID,prec->ID,sizeof(prec->ID));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [ID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameMacroName,prec->macroName,sizeof(prec->macroName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [macroName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameMacroValue,prec->macroValue,sizeof(prec->macroValue));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [macroValue] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameTableMenuType,&(prec->tableMenuType));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [tableMenuType] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameRemark,prec->remark,sizeof(prec->remark));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [remark] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameInputTeller,prec->inputTeller,sizeof(prec->inputTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTeller] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameInputDate,prec->inputDate,sizeof(prec->inputDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputDate] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameInputTime,prec->inputTime,sizeof(prec->inputTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTime] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameUpdateTeller,prec->updateTeller,sizeof(prec->updateTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTeller] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameUpdateDate,prec->updateDate,sizeof(prec->updateDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateDate] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameUpdateTime,prec->updateTime,sizeof(prec->updateTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormOperationListRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTime] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	return(0);
}


/*
功能：
	插入一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionInsertOperationListRec(PUnionOperationList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormRecStrFromOperationListRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertOperationListRec:: UnionFormRecStrFromOperationListRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//插入记录
	if ((ret = UnionInsertObjectRecord(conTBLNameOperationList,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionInsertOperationListRec:: UnionInsertObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	删除一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionDeleteOperationListRec(PUnionOperationList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormRecStrFromOperationListRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionDeleteOperationListRec:: UnionFormRecStrFromOperationListRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//删除记录
	if ((ret = UnionDeleteUniqueObjectRecord(conTBLNameOperationList,recStr)) < 0)
	{
		UnionUserErrLog("in UnionDeleteOperationListRec:: UnionDeleteUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	修改一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionUpdateOperationListRec(PUnionOperationList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormRecStrFromOperationListRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateOperationListRec:: UnionFormRecStrFromOperationListRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameOperationList,recStr,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateOperationListRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	读取一个记录
输入参数:
	prec	记录指针，必须对关键字域赋值
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadOperationListRec(PUnionOperationList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((ret = UnionFormRecStrFromOperationListRec(prec,condition,sizeof(condition))) < 0)
	{
		UnionUserErrLog("in UnionReadOperationListRec:: UnionFormRecStrFromOperationListRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	//读取记录
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameOperationList,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadOperationListRec:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//从记录串拼装结构
	if ((ret = UnionFormOperationListRecFromRecStr(recStr,lenOfRecStr,prec)) < 0)
	{
		UnionUserErrLog("in UnionReadOperationListRec:: UnionFormOperationListRecFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(sizeof(*prec));
}

/*
功能：
	读取一个指定ID的操作的操作宏定义值
输入参数:
	ID		用户分配置的操作ID
输出参数:
	无
返回值
	>=0		操作宏定义值
	<0		失败,错误码
*/
int UnionReadServiceIDByOperationName(char *ID)
{
	int	ret;
	TUnionOperationList	rec;
	int	retryTimes = 20;
	char	macroName[128+1];
	char	macroValue[128+1];
	
	memset(&rec,0,sizeof(rec));
	strcpy(rec.ID,ID);
	if ((ret = UnionReadOperationListRec(&rec)) < 0)
	{
		UnionUserErrLog("in UnionReadServiceIDByOperationName:: UnionReadOperationListRec [%d]!\n",ID);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	if (UnionIsDigitStr(rec.macroValue) || (rec.macroValue[0] == '-'))
		return(atoi(rec.macroValue));

	strcpy(macroName,rec.macroValue);
	for (; retryTimes > 0; retryTimes--)
	{	
		memset(macroValue,0,sizeof(macroValue));
		if ((ret = UnionReadOperationMacroValueByMacroName(macroName,macroValue)) < 0)
		{
			UnionUserErrLog("in UnionReadServiceIDByOperationName:: UnionReadOperationMacroValueByMacroName [%d]!\n",ID);
			return(UnionSetUserDefinedErrorCode(ret));
		}
		if (UnionIsDigitStr(macroValue) || (macroValue[0] == '-'))
		{
			UnionLog("in UnionReadServiceIDByOperationName:: ID = [%s] Value = [%s]\n",ID,macroValue);
			return(atoi(macroValue));
		}
		UnionLog("in UnionReadServiceIDByOperationName:: ***  ID = [%s] Value = [%s]\n",macroName,macroValue);
		strcpy(macroName,macroValue);
	}
	UnionUserErrLog("in UnionReadServiceIDByOperationName:: ID [%s] not defined!\n",ID);
	return(errCodeParameter);
}

/*
功能：
	读取一个指定操作宏定义值对应的操作名称
输入参数:
	int		serviceID
输出参数:
	ID		用户分配置的操作ID
返回值
	>=0		操作宏定义值
	<0		失败,错误码
*/
int UnionReadOperationNameByServiceID(int serviceID,char *ID)
{
	int		ret;
	char		recStr[1024+1];
	int		lenOfRecStr;
	char		uniqueKey[1024+1];
	
	sprintf(uniqueKey,"%s=%d",conOperationListFldNameMacroValue,serviceID);
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByUniqueKey(conTBLNameOperationList,uniqueKey,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadOperationNameByServiceID:: UnionSelectUniqueObjectRecordByUniqueKey [%s]!\n",uniqueKey);
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	if ((ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameID,ID,41)) < 0)
	{
		UnionUserErrLog("in UnionReadOperationNameByServiceID:: UnionReadRecFldFromRecStr [%s] from [%s]!\n",conOperationListFldNameID,recStr);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	return(0);
}

/*
功能：
	读取一个指定操作宏定义对应的宏定义值
输入参数:
	int		serviceID
输出参数:
	ID		用户分配置的操作ID
返回值
	>=0		宏定义值长度
	<0		失败,错误码
*/
int UnionReadOperationMacroValueByMacroName(char *macroDef,char *macroValue)
{
	int		ret;
	char		recStr[1024+1];
	int		lenOfRecStr;
	char		uniqueKey[1024+1];
	
	sprintf(uniqueKey,"%s=%s",conOperationListFldNameMacroName,macroDef);
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByUniqueKey(conTBLNameOperationList,uniqueKey,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadOperationMacroValueByMacroName:: UnionSelectUniqueObjectRecordByUniqueKey [%s]!\n",uniqueKey);
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	if ((ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameMacroValue,macroValue,128+1)) < 0)
	{
		UnionUserErrLog("in UnionReadOperationMacroValueByMacroName:: UnionReadRecFldFromRecStr [%s] from [%s]!\n",conOperationListFldNameMacroValue,recStr);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	return(ret);
}

/*
功能：
	读取一个指定操作宏定义对应的宏定义值
输入参数:
	int		serviceID
输出参数:
	无
返回值
	>=0		宏定义值
	<0		失败,错误码
*/
int UnionReadIntTypeOperationMacroValueByMacroName(char *macroDef)
{
	int		ret;
	char		recStr[1024+1];
	int		lenOfRecStr;
	char		uniqueKey[1024+1];
	char		macroValue[40+1];
	
	sprintf(uniqueKey,"%s=%s",conOperationListFldNameMacroName,macroDef);
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByUniqueKey(conTBLNameOperationList,uniqueKey,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadOperationMacroValueByMacroName:: UnionSelectUniqueObjectRecordByUniqueKey [%s]!\n",uniqueKey);
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	memset(macroValue,0,sizeof(macroValue));
	if ((ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conOperationListFldNameMacroValue,macroValue,sizeof(macroValue))) < 0)
	{
		UnionUserErrLog("in UnionReadOperationMacroValueByMacroName:: UnionReadRecFldFromRecStr [%s] from [%s]!\n",conOperationListFldNameMacroValue,recStr);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	if (UnionIsDigitStr(macroValue) || (macroValue[0] == '-'))
		return(atoi(macroValue));
	return(UnionReadIntTypeOperationMacroValueByMacroName(macroValue));
}

/*
功能：
	获得操作的界面操作类型
输入参数:
	ID		用户分配置的操作ID
输出参数:
	无
返回值
	>=0		操作的界面操作类型
	<0		失败,错误码
*/
int UnionGetOperationMenuType(char *ID)
{
	int	ret;
	TUnionOperationList	rec;
	
	memset(&rec,0,sizeof(rec));
	strcpy(rec.ID,ID);
	if ((ret = UnionReadOperationListRec(&rec)) < 0)
	{
		UnionUserErrLog("in UnionIsFormPopmenuOperation:: UnionReadOperationListRec [%s]!\n",ID);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	//UnionLog("in UnionGetOperationMenuType:: tableMenuType = [%d] of [%s]\n",rec.tableMenuType,ID);
	return(rec.tableMenuType);
}
