// Automatically generated codes
// Generated Date and Time 20090503125419
// Generated by ud090401

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "UnionLog.h"
#include "UnionStr.h"
#include "unionErrCode.h"
#include "unionDataTBLList.h"
#include "unionComplexDBRecord.h"

#include "unionTableList.h"
#include "unionMenuItemType.h"
#include "unionComplexDBRecord.h"

/*
功能：
	读取一个记录
输入参数:
	resID	资源ID
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadTableListRecByResID(int resID,PUnionTableList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	sprintf(condition,"%s=%d|",conTableListFldNameResID,resID);
	memset(recStr,0,sizeof(recStr));

	//读取记录
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByUniqueKey(conTBLNameTableList,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadTableListRecByResID:: UnionSelectUniqueObjectRecordByUniqueKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//从记录串拼装结构
	if ((ret = UnionFormTableListRecFromRecStr(recStr,lenOfRecStr,prec)) < 0)
	{
		UnionUserErrLog("in UnionReadTableListRecByResID:: UnionFormTableListRecFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(sizeof(*prec));
}

/*
功能：
	读取一个记录域
输入参数:
	resID		资源ID
	fldName		域名称
	sizeOfFldValue	取值域的大小
输出参数:
	fldValue	读到的域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadTableListRecFldByResID(int resID,char *fldName,char *fldValue,int sizeOfFldValue)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	condition[256+1];
	
	//从记录拼装串
	sprintf(condition,"%s=%d|",conTableListFldNameResID,resID);
	memset(recStr,0,sizeof(recStr));
	//读取记录
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByUniqueKey(conTBLNameTableList,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadTableListRecFldByResID:: UnionSelectUniqueObjectRecordByUniqueKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	return(UnionReadRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue,sizeOfFldValue));
}

/*
功能：
	读取一个记录域
输入参数:
	tableName	表名称
	fldName		域名称
	sizeOfFldValue	取值域的大小
输出参数:
	fldValue	读到的域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadTableListRecFld(char *tableName,char *fldName,char *fldValue,int sizeOfFldValue)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	condition[256+1];

	//从记录拼装串
	sprintf(condition,"%s=%s|",conTableListFldNameTableName,tableName);
	memset(recStr,0,sizeof(recStr));
	//读取记录
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameTableList,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadTableListRecFld:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	return(UnionReadRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue,sizeOfFldValue));
}

/*
功能：
	结构的缺省赋值函数
输入参数:
	prec	记录指针
输出参数:
	无
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormDefaultValueOfTableListRec(PUnionTableList prec)
{
	int	ret;

	if (prec == NULL)
	{
		UnionUserErrLog("in UnionFormDefaultValueOfTableListRec:: prec is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	memset(prec,0,sizeof(*prec));
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormPrimaryKeyRecStrFromTableListRec(PUnionTableList prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromTableListRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameTableName,prec->tableName,strlen(prec->tableName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [tableName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}

/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormNonePrimaryKeyRecStrFromTableListRec(PUnionTableList prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr("formMenuItemList",prec->formMenuItemList,strlen(prec->formMenuItemList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [formMenuItemList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr("recMenuItemList",prec->recMenuItemList,strlen(prec->recMenuItemList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [recMenuItemList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr("doubleClickMenuItemList",prec->doubleClickMenuItemList,strlen(prec->doubleClickMenuItemList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [doubleClickMenuItemList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameTableTypeID,prec->tableTypeID,strlen(prec->tableTypeID),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [tableTypeID] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameTableAlais,prec->tableAlais,strlen(prec->tableAlais),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [tableAlais] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conTableListFldNameResID,prec->resID,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutIntTypeRecFldIntoRecStr [resID] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameRemark,prec->remark,strlen(prec->remark),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [remark] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameFieldList,prec->fieldList,strlen(prec->fieldList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [fieldList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNamePrimaryKey,prec->primaryKey,strlen(prec->primaryKey),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [primaryKey] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameUnique1,prec->unique1,strlen(prec->unique1),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [unique1] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameUnique2,prec->unique2,strlen(prec->unique2),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [unique2] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameUnique3,prec->unique3,strlen(prec->unique3),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [unique3] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameUnique4,prec->unique4,strlen(prec->unique4),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [unique4] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameMyKeyGrp1,prec->myKeyGrp1,strlen(prec->myKeyGrp1),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [myKeyGrp1] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameForeignTable1,prec->foreignTable1,strlen(prec->foreignTable1),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [foreignTable1] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameForeignKey1,prec->foreignKey1,strlen(prec->foreignKey1),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [foreignKey1] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameMyKeyGrp2,prec->myKeyGrp2,strlen(prec->myKeyGrp2),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [myKeyGrp2] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameForeignTable2,prec->foreignTable2,strlen(prec->foreignTable2),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [foreignTable2] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameForeignKey2,prec->foreignKey2,strlen(prec->foreignKey2),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [foreignKey2] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameMyKeyGrp3,prec->myKeyGrp3,strlen(prec->myKeyGrp3),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [myKeyGrp3] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameForeignTable3,prec->foreignTable3,strlen(prec->foreignTable3),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [foreignTable3] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameForeignKey3,prec->foreignKey3,strlen(prec->foreignKey3),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [foreignKey3] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameMyKeyGrp4,prec->myKeyGrp4,strlen(prec->myKeyGrp4),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [myKeyGrp4] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameForeignTable4,prec->foreignTable4,strlen(prec->foreignTable4),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [foreignTable4] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameForeignKey4,prec->foreignKey4,strlen(prec->foreignKey4),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [foreignKey4] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameOperationList,prec->operationList,strlen(prec->operationList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [operationList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameInitValueList,prec->initValueList,strlen(prec->initValueList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [initValueList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameInputTeller,prec->inputTeller,strlen(prec->inputTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [inputTeller] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameInputDate,prec->inputDate,strlen(prec->inputDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [inputDate] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameInputTime,prec->inputTime,strlen(prec->inputTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [inputTime] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameUpdateTeller,prec->updateTeller,strlen(prec->updateTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [updateTeller] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameUpdateDate,prec->updateDate,strlen(prec->updateDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [updateDate] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conTableListFldNameUpdateTime,prec->updateTime,strlen(prec->updateTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionPutRecFldIntoRecStr [updateTime] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}

/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormRecStrFromTableListRec(PUnionTableList prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;
	
	if ((ret = UnionFormPrimaryKeyRecStrFromTableListRec(prec,recStr+offset,sizeOfBuf-offset)) < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionFormPrimaryKeyRecStrFromTableListRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;

	if ((ret = UnionFormNonePrimaryKeyRecStrFromTableListRec(prec,recStr+offset,sizeOfBuf-offset)) < 0)
	{
		UnionUserErrLog("in UnionFormNonePrimaryKeyRecStrFromTableListRec:: UnionFormNonePrimaryKeyRecStrFromTableListRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(ret);
}

/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormTableListRecFromRecStr(char *recStr,int lenOfRecStr,PUnionTableList prec)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormTableListRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfTableListRec(prec);
	
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,"formMenuItemList",prec->formMenuItemList,sizeof(prec->formMenuItemList));
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,"recMenuItemList",prec->recMenuItemList,sizeof(prec->recMenuItemList));
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,"doubleClickMenuItemList",prec->doubleClickMenuItemList,sizeof(prec->doubleClickMenuItemList));

	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameTableName,prec->tableName,sizeof(prec->tableName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [tableName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameTableTypeID,prec->tableTypeID,sizeof(prec->tableTypeID));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [tableTypeID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameTableAlais,prec->tableAlais,sizeof(prec->tableAlais));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [tableAlais] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameResID,&(prec->resID));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [resID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameRemark,prec->remark,sizeof(prec->remark));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [remark] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameFieldList,prec->fieldList,sizeof(prec->fieldList));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [fieldList] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNamePrimaryKey,prec->primaryKey,sizeof(prec->primaryKey));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [primaryKey] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameUnique1,prec->unique1,sizeof(prec->unique1));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [unique1] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameUnique2,prec->unique2,sizeof(prec->unique2));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [unique2] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameUnique3,prec->unique3,sizeof(prec->unique3));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [unique3] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameUnique4,prec->unique4,sizeof(prec->unique4));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [unique4] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameMyKeyGrp1,prec->myKeyGrp1,sizeof(prec->myKeyGrp1));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [myKeyGrp1] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameForeignTable1,prec->foreignTable1,sizeof(prec->foreignTable1));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [foreignTable1] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameForeignKey1,prec->foreignKey1,sizeof(prec->foreignKey1));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [foreignKey1] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameMyKeyGrp2,prec->myKeyGrp2,sizeof(prec->myKeyGrp2));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [myKeyGrp2] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameForeignTable2,prec->foreignTable2,sizeof(prec->foreignTable2));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [foreignTable2] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameForeignKey2,prec->foreignKey2,sizeof(prec->foreignKey2));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [foreignKey2] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameMyKeyGrp3,prec->myKeyGrp3,sizeof(prec->myKeyGrp3));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [myKeyGrp3] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameForeignTable3,prec->foreignTable3,sizeof(prec->foreignTable3));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [foreignTable3] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameForeignKey3,prec->foreignKey3,sizeof(prec->foreignKey3));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [foreignKey3] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameMyKeyGrp4,prec->myKeyGrp4,sizeof(prec->myKeyGrp4));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [myKeyGrp4] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameForeignTable4,prec->foreignTable4,sizeof(prec->foreignTable4));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [foreignTable4] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameForeignKey4,prec->foreignKey4,sizeof(prec->foreignKey4));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [foreignKey4] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameOperationList,prec->operationList,sizeof(prec->operationList));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [operationList] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameInitValueList,prec->initValueList,sizeof(prec->initValueList));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [initValueList] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameInputTeller,prec->inputTeller,sizeof(prec->inputTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTeller] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameInputDate,prec->inputDate,sizeof(prec->inputDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputDate] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameInputTime,prec->inputTime,sizeof(prec->inputTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTime] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameUpdateTeller,prec->updateTeller,sizeof(prec->updateTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTeller] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameUpdateDate,prec->updateDate,sizeof(prec->updateDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateDate] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conTableListFldNameUpdateTime,prec->updateTime,sizeof(prec->updateTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormTableListRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTime] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	return(0);
}


/*
功能：
	插入一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionInsertTableListRec(PUnionTableList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((ret = UnionPutRecFldIntoRecStr("reservedRes","1",1,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertTableListRec:: UnionPutRecFldIntoRecStr reservedRes!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	if ((lenOfRecStr = UnionFormRecStrFromTableListRec(prec,recStr+ret,sizeof(recStr)-ret)) < 0)
	{
		UnionUserErrLog("in UnionInsertTableListRec:: UnionFormRecStrFromTableListRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	//插入记录
	if ((ret = UnionInsertObjectRecord(conTBLNameTableList,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionInsertTableListRec:: UnionInsertObjectRecord! [%04d][%s]\n",lenOfRecStr,recStr);
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	删除一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionDeleteTableListRec(PUnionTableList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormPrimaryKeyRecStrFromTableListRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionDeleteTableListRec:: UnionFormPrimaryKeyRecStrFromTableListRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//删除记录
	if ((ret = UnionDeleteUniqueObjectRecord(conTBLNameTableList,recStr)) < 0)
	{
		UnionUserErrLog("in UnionDeleteTableListRec:: UnionDeleteUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	修改一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionUpdateTableListRec(PUnionTableList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	primaryKey[1024+1];
	
	//从记录拼装串
	memset(primaryKey,0,sizeof(primaryKey));
	if ((lenOfRecStr = UnionFormPrimaryKeyRecStrFromTableListRec(prec,primaryKey,sizeof(primaryKey))) < 0)
	{
		UnionUserErrLog("in UnionUpdateTableListRec:: UnionFormPrimaryKeyRecStrFromTableListRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	UnionLog("in UnionUpdateTableListRec:: primaryKey=[%04d][%s]\n",lenOfRecStr,primaryKey);
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormNonePrimaryKeyRecStrFromTableListRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateTableListRec:: UnionFormNonePrimaryKeyRecStrFromTableListRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	UnionLog("in UnionUpdateTableListRec:: recStr=[%04d][%s]\n",lenOfRecStr,recStr);
	//修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameTableList,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateTableListRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	UnionLog("in UnionUpdateTableListRec:: UnionUpdateUniqueObjectRecord OK\n",lenOfRecStr,recStr);
	return(ret);
}


/*
功能：
	读取一个记录
输入参数:
	prec	记录指针，必须对关键字域赋值
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadTableListRec(PUnionTableList prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((ret = UnionFormPrimaryKeyRecStrFromTableListRec(prec,condition,sizeof(condition))) < 0)
	{
		UnionUserErrLog("in UnionReadTableListRec:: UnionFormPrimaryKeyRecStrFromTableListRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	//读取记录
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameTableList,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadTableListRec:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//从记录串拼装结构
	if ((ret = UnionFormTableListRecFromRecStr(recStr,lenOfRecStr,prec)) < 0)
	{
		UnionUserErrLog("in UnionReadTableListRec:: UnionFormTableListRecFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(sizeof(*prec));
}

/*
功能：
	根据表名称读取表的版本
输入参数:
	tableName	表名称
	sizeOfBuf	接收缓冲的大小
输出参数:
	version
返回值
	>=0		成功，返回版本的长度
	<0		失败,错误码
*/
int UnionReadTableListRecVersionOfSpecTBLName(char *tableName,char *version,int sizeOfBuf)
{

	char	condition[256+1];
	int	len;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	// 拼查询条件串
	memset(condition,0,sizeof(condition));
	UnionPutRecFldIntoRecStr("tableName",tableName,strlen(tableName),condition,sizeof(condition));
	
	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameTableList,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadTableListRecVersionOfSpecTBLName:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	return(UnionReadRecFldFromRecStr(recStr,lenOfRecStr,"version",version,sizeOfBuf));
}

/*
功能：
	根据表名称读取一个记录
输入参数:
	tableName	表名称
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadTableListRecOfSpecTBLName(char *tableName,PUnionTableList prec)
{
	if ((tableName == NULL) || (prec == NULL) || (strlen(tableName) >= sizeof(prec->tableName)))
	{
		UnionUserErrLog("in UnionReadTableListRecOfSpecTBLName:: null pointer!\n");
		return(errCodeParameter);
	}
	strcpy(prec->tableName,tableName);
	return(UnionReadTableListRec(prec));
}

/*
功能：
	根据表名称读取一个表的RESID
输入参数:
	tableName	表名称
输出参数:
	无
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadResIDOfSpecTBLName(char *tableName)
{
	TUnionTableList	rec;
	int		ret;
	
	memset(&rec,0,sizeof(rec));
	if ((ret = UnionReadTableListRecOfSpecTBLName(tableName,&rec)) < 0)
	{
		UnionUserErrLog("in UnionReadTableListRecOfSpecTBLName:: UnionReadTableListRecOfSpecTBLName! [%s]\n",tableName);
		return(ret);
	}
	return(rec.resID);
}

/*
功能：
	根据表名称读取表的别名
输入参数:
	tableName	表名称
输出参数:
	tableAlais	表别名
返回值
	>=0		成功
	<0		失败,错误码
*/
int UnionReadTableAlaisOfSpecTBLName(char *tableName,char *tableAlais)
{
	TUnionTableList	rec;
	int		ret;
	
	memset(&rec,0,sizeof(rec));
	if ((ret = UnionReadTableListRecOfSpecTBLName(tableName,&rec)) < 0)
	{
		UnionUserErrLog("in UnionReadTableAlaisOfSpecTBLName:: UnionReadTableListRecOfSpecTBLName [%s]!\n",tableName);
		return(ret);
	}
	strcpy(tableAlais,rec.tableAlais);
	return(0);
}

/*
功能：
	将一个操作，增加到表的菜单项中
输入参数:
	tableName	表名称
	menuItemName	菜单项名称
	menuType	菜单项类型
输出参数:
	无
返回值
	>=0		成功
	<0		失败,错误码
*/
int UnionAppendMenuItemToSpecTBLName(char *tableName,char *menuItemName,int menuType)
{
	int			ret;
	char			*fldList;
	TUnionTableList		rec;
	int			sizeOfBuf;
	int			oriLen;
	
	memset(&rec,0,sizeof(rec));
	strcpy(rec.tableName,tableName);
	if ((ret = UnionReadTableListRec(&rec)) < 0)
	{
		UnionUserErrLog("in UnionAppendMenuItemToSpecTBLName:: UnionReadTableListRec!\n");
		return(ret);
	}
	switch (menuType)
	{
		case	conMenuItemTypeFormPopMenu:
			fldList = rec.formMenuItemList;
			sizeOfBuf = sizeof(rec.formMenuItemList);
			break;
		case	conMenuItemTypeRecPopMenu:
			fldList = rec.recMenuItemList;
			sizeOfBuf = sizeof(rec.recMenuItemList);
			break;
		case	conMenuItemTypeDoubleClickMenu:
			fldList = rec.doubleClickMenuItemList;
			sizeOfBuf = sizeof(rec.doubleClickMenuItemList);
			break;
		default:
			UnionUserErrLog("in UnionAppendMenuItemToSpecTBLName:: invalid menutype [%d]\n",menuType);
			return(errCodeParameter);
	}
	UnionLog("in UnionAppendMenuItemToSpecTBLName::fldList = [%s] sizeOfBuf = [%d]\n",fldList,sizeOfBuf);
	if ((ret = UnionIsFldStrInUnionFldListStr(fldList,oriLen = strlen(fldList),',',menuItemName)) < 0)
	{
		UnionUserErrLog("in UnionAppendMenuItemToSpecTBLName:: UnionIsFldStrInUnionFldListStr [%s]!\n",fldList);
		return(ret);
	}
	UnionLog("in UnionAppendMenuItemToSpecTBLName::fldList = [%s] oriLen = [%d]\n",fldList,oriLen);
	if (ret > 0)
	{
		//UnionProgramerLog("in UnionAppendMenuItemToSpecTBLName:: [%s] already in [%s] of table [%s]\n",menuItemName,fldList,tableName);
		UnionUserErrLog("in UnionAppendMenuItemToSpecTBLName:: [%s] already in [%s] of table [%s]\n",menuItemName,fldList,tableName);
		return(0);
	}
	if (strlen(menuItemName)+1+oriLen >= sizeOfBuf)
	{
		UnionUserErrLog("in UnionAppendMenuItemToSpecTBLName:: [%s] is too long!\n",fldList);
		return(errCodeObjectMDL_FieldValueTooLong);
	}
	if (oriLen > 0)
	{
		sprintf(fldList+oriLen,",");
		oriLen++;
	}
	sprintf(fldList+oriLen,"%s",menuItemName);
	UnionLog("in UnionAppendMenuItemToSpecTBLName::fldList = [%s]\n",fldList);
	if ((ret = UnionUpdateTableListRec(&rec)) < 0)
	{
		UnionUserErrLog("in UnionAppendMenuItemToSpecTBLName:: UnionUpdateTableListRec [%s]!\n",tableName);
		return(ret);
	}
	UnionLog("in UnionAppendMenuItemToSpecTBLName::UnionUpdateTableListRec = [%s] OK\n",tableName);
	return(ret);
}

