// Automatically generated codes
// Generated Date and Time 20100402150724
// Generated by ud090401

#ifndef _unionMainMenu_struct_20090421_
#define _unionMainMenu_struct_20090421_
#endif

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "UnionLog.h"
#include "UnionStr.h"
#include "unionErrCode.h"
#include "unionComplexDBRecord.h"
#include "unionDataTBLList.h"

#include "unionMainMenu.h"


/*
功能：
	结构的缺省赋值函数
输入参数:
	prec	记录指针
输出参数:
	无
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormDefaultValueOfMainMenuRec(PUnionMainMenu prec)
{
	int	ret;

	if (prec == NULL)
	{
		UnionUserErrLog("in UnionFormDefaultValueOfMainMenuRec:: prec is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	memset(prec,0,sizeof(*prec));
	return(0);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormRecStrFromMainMenuRec(PUnionMainMenu prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormRecStrFromMainMenuRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	if ((ret = UnionFormPrimaryKeyRecStrFromMainMenuRec(prec,recStr,sizeOfBuf)) < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromMainMenuRec:: UnionFormPrimaryKeyRecStrFromMainMenuRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset = ret;
	if ((ret = UnionFormNonPrimaryKeyRecStrFromMainMenuRec(prec,recStr+offset,sizeOfBuf-offset)) < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromMainMenuRec:: UnionFormNonPrimaryKeyRecStrFromMainMenuRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormPrimaryKeyRecStrFromMainMenuRec(PUnionMainMenu prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMainMenuRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameMainMenuName,prec->mainMenuName,strlen(prec->mainMenuName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [mainMenuName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormNonPrimaryKeyRecStrFromMainMenuRec(PUnionMainMenu prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameMainMenuItemsList,prec->mainMenuItemsList,strlen(prec->mainMenuItemsList),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [mainMenuItemsList] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameProjectID,prec->projectID,strlen(prec->projectID),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [projectID] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMainMenuFldNameUseMenuItemButton,prec->useMenuItemButton,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutIntTypeRecFldIntoRecStr [useMenuItemButton] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMainMenuFldNameUseServerMenu,prec->useServerMenu,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutIntTypeRecFldIntoRecStr [useServerMenu] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameRemark,prec->remark,strlen(prec->remark),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [remark] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameInputTeller,prec->inputTeller,strlen(prec->inputTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [inputTeller] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameInputDate,prec->inputDate,strlen(prec->inputDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [inputDate] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameInputTime,prec->inputTime,strlen(prec->inputTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [inputTime] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameUpdateTeller,prec->updateTeller,strlen(prec->updateTeller),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [updateTeller] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameUpdateDate,prec->updateDate,strlen(prec->updateDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [updateDate] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameUpdateTime,prec->updateTime,strlen(prec->updateTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [updateTime] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMainMenuFldNameIconFileName,prec->iconFileName,strlen(prec->iconFileName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMainMenuRec:: UnionPutRecFldIntoRecStr [iconFileName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录字串转换为记录结构的关键字的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormPrimaryKeyOfMainMenuRecFromRecStr(char *recStr,int lenOfRecStr,PUnionMainMenu prec)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormPrimaryKeyOfMainMenuRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfMainMenuRec(prec);
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameMainMenuName,prec->mainMenuName,sizeof(prec->mainMenuName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [mainMenuName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	return(0);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormMainMenuRecFromRecStr(char *recStr,int lenOfRecStr,PUnionMainMenu prec)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfMainMenuRec(prec);
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameMainMenuName,prec->mainMenuName,sizeof(prec->mainMenuName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [mainMenuName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameMainMenuItemsList,prec->mainMenuItemsList,sizeof(prec->mainMenuItemsList));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [mainMenuItemsList] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameProjectID,prec->projectID,sizeof(prec->projectID));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [projectID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameUseMenuItemButton,&(prec->useMenuItemButton));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [useMenuItemButton] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameUseServerMenu,&(prec->useServerMenu));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [useServerMenu] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameRemark,prec->remark,sizeof(prec->remark));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [remark] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameInputTeller,prec->inputTeller,sizeof(prec->inputTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTeller] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameInputDate,prec->inputDate,sizeof(prec->inputDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputDate] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameInputTime,prec->inputTime,sizeof(prec->inputTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTime] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameUpdateTeller,prec->updateTeller,sizeof(prec->updateTeller));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTeller] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameUpdateDate,prec->updateDate,sizeof(prec->updateDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateDate] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameUpdateTime,prec->updateTime,sizeof(prec->updateTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [updateTime] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMainMenuFldNameIconFileName,prec->iconFileName,sizeof(prec->iconFileName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMainMenuRecFromRecStr:: UnionReadRecFldFromRecStr fld [iconFileName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	return(0);
}


/*
功能：
	插入一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionInsertMainMenuRec(PUnionMainMenu prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormRecStrFromMainMenuRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertMainMenuRec:: UnionFormRecStrFromMainMenuRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//赋加自动插入域
	if ((lenOfRecStr = UnionAutoAppendDBRecInputAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertMainMenuRec:: UnionAutoAppendDBRecInputAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//插入记录
	if ((ret = UnionInsertObjectRecord(conTBLNameMainMenu,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionInsertMainMenuRec:: UnionInsertObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	删除一个记录
输入参数:
	mainMenuName 主菜单名称
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionDeleteMainMenuRec(char *mainMenuName)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteMainMenuRec:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	//删除记录
	if ((ret = UnionDeleteUniqueObjectRecord(conTBLNameMainMenu,recStr)) < 0)
	{
		UnionUserErrLog("in UnionDeleteMainMenuRec:: UnionDeleteUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	修改一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionUpdateMainMenuRec(PUnionMainMenu prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	primaryKey[1024+1];

	//从记录拼关键字
	memset(primaryKey,0,sizeof(primaryKey));
	if ((ret = UnionFormPrimaryKeyRecStrFromMainMenuRec(prec,primaryKey,sizeof(primaryKey))) < 0)
	{
		UnionUserErrLog("in UnionUpdateMainMenuRec:: UnionFormPrimaryKeyRecStrFromMainMenuRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	//从记录接记录串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormNonPrimaryKeyRecStrFromMainMenuRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateMainMenuRec:: UnionFormNonPrimaryKeyRecStrFromMainMenuRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateMainMenuRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameMainMenu,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateMainMenuRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}
/*
函数功能:
	修改指定的表域:
输入参数:
	mainMenuName 主菜单名称
	fldName 域名称
	fldValue 域值
	fldValueLen 域值长度
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateSpecFldOfMainMenuRec(char *mainMenuName,char *fldName,char *fldValue,int lenOfFldValue)
{
	int	ret;
	char	recStr[8192*2+1];
	char	primaryKey[1024+1];
	int	lenOfRecStr = 0;

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMainMenuRec:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	strcpy(primaryKey,recStr);

	// 组记录
	memset(recStr,0,sizeof(recStr));
	lenOfRecStr = 0;
	if ((ret = UnionPutRecFldIntoRecStr(fldName,fldValue,lenOfFldValue,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMainMenuRec:: UnionPutRecFldIntoRecStr [%s] failure!\n",fldName);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMainMenuRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	// 修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameMainMenu,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMainMenuRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}

/*
函数功能:
	修改指定的表域:
输入参数:
	mainMenuName 主菜单名称
	fldName 域名称
	fldValue 域值
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateIntTypeSpecFldOfMainMenuRec(char *mainMenuName,char *fldName,int fldValue)
{
	int	ret;
	char	recStr[8192*2+1];
	char	primaryKey[1024+1];
	int	lenOfRecStr = 0;

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMainMenuRec:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	strcpy(primaryKey,recStr);

	// 组记录
	memset(recStr,0,sizeof(recStr));
	lenOfRecStr = 0;
	if ((ret = UnionPutIntTypeRecFldIntoRecStr(fldName,fldValue,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMainMenuRec:: UnionPutIntTypeRecFldIntoRecStr [%s] failure!\n",fldName);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMainMenuRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	// 修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameMainMenu,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMainMenuRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}



/*
功能：
	读取一个记录
输入参数:
	mainMenuName 主菜单名称
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadMainMenuRec(char *mainMenuName,PUnionMainMenu prec)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMainMenuRec:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadMainMenuRec:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameMainMenu,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadMainMenuRec:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//从记录串拼装结构
	if ((ret = UnionFormMainMenuRecFromRecStr(recStr,lenOfRecStr,prec)) < 0)
	{
		UnionUserErrLog("in UnionReadMainMenuRec:: UnionFormMainMenuRecFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(sizeof(*prec));
}


/*
功能：
	读取一个记录
输入参数:
	mainMenuName 主菜单名称
	fldName		域名
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadMainMenuRecIntTypeFld(char *mainMenuName,char *fldName,int *fldValue)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMainMenuRecIntTypeFld:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadMainMenuRecIntTypeFld:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameMainMenu,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadMainMenuRecIntTypeFld:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//读指定域
	if ((ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue)) < 0)
	{
		UnionUserErrLog("in UnionReadMainMenuRecIntTypeFld:: UnionReadIntTypeRecFldFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	读取一个记录
输入参数:
	mainMenuName 主菜单名称
	fldName		域名
	sizeOfBuf	域值缓冲大小
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadMainMenuRecFld(char *mainMenuName,char *fldName,char *fldValue,int sizeOfBuf)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("mainMenuName",mainMenuName,strlen(mainMenuName),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMainMenuRecFld:: UnionPutRecFldIntoRecStr [mainMenuName] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadMainMenuRecFld:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameMainMenu,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadMainMenuRecFld:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//读指定域
	if ((ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue,sizeOfBuf)) < 0)
	{
		UnionUserErrLog("in UnionReadMainMenuRecFld:: UnionReadRecFldFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	根据条件，批量读取数据
输入参数:
	condition	条件字串
	maxRecNum		读取的最大记录数量
输出参数:
	recGrp		记录数组
返回值
	>=0		成功,读取的记录数量
	<0		失败,错误码
*/
int UnionBatchReadMainMenuRec(char *condition,TUnionMainMenu recGrp[],int maxRecNum)
{
	int	ret;
	char	fileName[512+1];
	int	recNum = 0;
	FILE	*recFileFp = NULL;
	char	recStr[8192*2+1];
	int	lenOfRecStr;
	char	tableName[128+1];
	TUnionMainMenu	rec;

	memset(fileName,0,sizeof(fileName));
	sprintf(fileName,"%s/pid-%d.tmp",getenv("UNIONTEMP"),getpid());

// 读所有记录
	if ((ret = UnionBatchSelectObjectRecord(conTBLNameMainMenu,condition,fileName)) < 0)
	{
		UnionUserErrLog("in UnionBatchReadMainMenuRec:: UnionBatchSelectObjectRecord from [%s] on [%s]!\n",conTBLNameMainMenu,condition);
		return(ret);
	}
	// 打开文件
	if ((recFileFp = fopen(fileName,"r")) == NULL)
	{
		UnionUserErrLog("in UnionBatchReadMainMenuRec:: fopen [%s]\n",fileName);
		goto errExit;
	}
	while (!feof(recFileFp))
	{
		if (recNum >= maxRecNum)
		{
			UnionLog("in UnionBatchReadMainMenuRec:: still exists records satisfy the condition [%s]!\n",condition);
			ret = recNum;
			goto errExit;
		}
		memset(recStr,0,sizeof(recStr));
		if ((lenOfRecStr = UnionReadOneDataLineFromTxtFile(recFileFp,recStr,sizeof(recStr))) <= 0)
			continue;
		memset(&rec,0,sizeof(rec));
		if ((ret = UnionFormMainMenuRecFromRecStr(recStr,lenOfRecStr,&rec)) < 0)
		{
			UnionUserErrLog("in UnionBatchReadMainMenuRec:: UnionFormMainMenuRecFromRecStr from [%04d] [%s]\n",lenOfRecStr,recStr);
			goto errExit;
		}
		memcpy(&(recGrp[recNum]),&rec,sizeof(rec));
		recNum++;
	}
	ret = recNum;
errExit:
	fclose(recFileFp);
	UnionDeleteFile(fileName);
	return(ret);

}
