# 定义开发目录
HOMEDIR = $(UNIONLIBDIR)/unionVersion
INCDIR = $(HOMEDIR)include/
OBJDIR = $(CMM2003LIBDIR)

# 定义头文件目录清单
# 顺序应该是：
# 通用模块头文件目录/当前开发环境头文件目录/本工程的头文件目录

INCL = -I $(INCDIR) -I $(CMM2003INCDIR)	

#传给脚本的参数
SLP1 = "$*.o"	"$@ $*.o"	$@
# 这个编译开关必须增加
DEFINES = -D _UNIX $(OSSPEC)

COMPILE	= $(CC) $(DEFINES) $(INCL) -c
DEPEND	= $(CC) $(INCL) -MM -c

VPATH	= $(OBJDIR)

srcs	= $(wildcard *.c)
objs =	$(patsubst %.c,%.o,$(srcs)) 
deps =	$(patsubst %.c,%.d,$(srcs)) 

libs =	genVersionLib1.0.a	\
	genProductGenerateTime	\
	genVersionLib

all:	makeall

makeall:	$(objs)		\
		$(libs)

.SUFFIXES:.c.o
%.o:%.c
	@echo "CC $(DEFINES) $(OBJDIR)$@	$<"
	@$(COMPILE) $< -o $(OBJDIR)$@

$(OBJDIR)%.d:%.c
	@echo "DEP $@	$<"
	@$(DEPEND) $< > $@
	@sh file_substr.x $(SLP1)

.c.a:
	@echo "CC AND $(AR) $(DEFINES) $(OBJDIR)$@	$<"
	@$(COMPILE) $< -o $*.o
	@$(AR) $(OSSPECPACK) rv $(OBJDIR)$@ $*.o 
	@$(RM) $*.o

libs0110 = $(CMM2003LIBDIR)genProductGenerateTime1.0.o
genProductGenerateTime:
		@echo "building...	$@"
		@$(CC) $(DEFINES) -o $(CMM2003TOOLSDIR)$@ $(libs0110) $(OSSPECLIBS)

libs0310 =	$(CMM2003LIBDIR)genVersionLib1.0.a
genVersionLib:
		@echo "building...	$@"
		@$(CC) $(DEFINES) -o $(CMM2003TOOLSDIR)$@ $(libs0310) $(OSSPECLIBS)

ifeq ($(filter $(MAKECMDGOALS),clean install show),) 
ifeq ($(UNION_USE_GCC),1)
sinclude $(addprefix $(OBJDIR),$(deps))
endif
endif
	
.PHONY: clean install
install:
#	@sh cp_head.x  ../include/ $(CMM2003INCDIR)

clean:
	$(RM) $(addprefix $(OBJDIR),$(objs)) $(addprefix $(OBJDIR),$(libs)) $(addprefix $(OBJDIR),$(deps))
	$(RM) $(OBJDIR)genProductGenerateTime1.0.o
	
show:
	make -v
	@echo '=============================================================='
	@echo 'srcs	:' $(srcs)
	@echo 'objs	:' $(objs)
	@echo 'deps	:' $(deps)
	@echo 'INCL	:' $(INCL)
	@echo 'COMPILE	:' $(COMPILE)
	@echo 'DEPEND	:' $(DEPEND)
	
