#!/usr/bin/perl 
#############################################################################################
#脚本使用说明：将此脚本与需要被检查的文件放于同个目录下，直接运行脚本，按照提示输入文件名称
##################################################################################################
       #$line="int UnionSetIsKeyDBBackerUseLongConn(int flag)";
        print "please input filename:";
	chomp($filename=<STDIN>);
	open IN,$filename or die;
	#open LOGLIST,"list.txt" or die;
	@loglist=qw(UnionSystemErrLog UnionUserErrLog UnionSuccessLog UnionLog UnionAuditLog UnionNoTimeLog WriteMemory UnionMemErrLog UnionMemLog UnionPrintfg UnionNullLog);
	@line=<IN>;
	$lineno=1;
	$tag=0;
        foreach $line(@line)
	{        
                #匹配一个方法int uinonREC()
        	$isture=($line=~/(\w+)\s+(\**[Uu]nion\w+)\s*\((.*)\)$/);
        	if($isture)
         	{
                 	#print"$lineno\:\:the first is:$1 , the second is:$2,the third is $3\n"; 
                        $qcname=$2;
        		if($tag==1)
	           	{
		             $lastline=$lineno;
	                     # sed -n '1,2p'
	                     `sed -n "${firstline},${lastline}p" "$filename">transfortest` ;
                              open FINDLOG,transfortest or die;
                              @findlog=<FINDLOG>;
		             foreach $loglist(@loglist)
	   	             {
 
		                chomp($loglist);
		                #UnionUserErrLog("in UnionGetCurrentKeyDBBackupServer:: UnionConnectKeyDBBackupServer!\n");
                                $lineno_=0;
		                foreach $findlog(@findlog)

		                {
                                   chomp($findlog);
                                   $lineno_=$lineno_+1; 
       		                   $islog=($findlog=~/$loglist\s*\(".*\s+([Uu]nion\w+)\s*\:\:\s*([Uu]nion\w+)!/);
                                   if($islog)
                                   {
                                     
                                       if($cname ne $1 )
                                       {
                                         $lineno1=${firstline}+$lineno_-1;
                                         print"error in line:$lineno1;may be \"$1\" should be changed into \"$cname\"\n" ;
                                       }
                                   }
                                 
		                }
		              }
		              $tag=0;
		          }
		
		
		
		         if($tag==0)
		         {
		              $cname=$qcname;
		              # print "cname is $cname\n";
		               $firstline=$lineno;
		              $tag=$tag+1;
	                 }

	          }
		$lineno=$lineno+1;
	}
       if($lineno1 eq undef)
        {
          print"Congratulations!There is not error in your file.\n";
         }
