// Automatically generated codes
// Generated Date and Time 20090523221638
// Generated by ud090401

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "UnionLog.h"
#include "UnionStr.h"
#include "unionErrCode.h"
#include "unionComplexDBRecord.h"
#include "unionDataTBLList.h"

#include "unionMngServiceOnline.h"


/*
功能：
	结构的缺省赋值函数
输入参数:
	prec	记录指针
输出参数:
	无
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormDefaultValueOfMngServiceOnlineRec(PUnionMngServiceOnline prec)
{
	int	ret;

	if (prec == NULL)
	{
		UnionUserErrLog("in UnionFormDefaultValueOfMngServiceOnlineRec:: prec is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	memset(prec,0,sizeof(*prec));
	return(0);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormRecStrFromMngServiceOnlineRec(PUnionMngServiceOnline prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormRecStrFromMngServiceOnlineRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	if ((ret = UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec(prec,recStr,sizeOfBuf)) < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromMngServiceOnlineRec:: UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset = ret;
	if ((ret = UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec(prec,recStr+offset,sizeOfBuf-offset)) < 0)
	{
		UnionUserErrLog("in UnionFormRecStrFromMngServiceOnlineRec:: UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec(PUnionMngServiceOnline prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutCharTypeRecFldIntoRecStr(conMngServiceOnlineFldNameDirectionTag,prec->directionTag,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutCharTypeRecFldIntoRecStr [directionTag] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMngServiceOnlineFldNameDate,prec->date,strlen(prec->date),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [date] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMngServiceOnlineFldNameTime,prec->time,strlen(prec->time),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [time] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMngServiceOnlineFldNameClientIPAddr,prec->clientIPAddr,strlen(prec->clientIPAddr),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [clientIPAddr] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMngServiceOnlineFldNamePort,prec->port,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutIntTypeRecFldIntoRecStr [port] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMngServiceOnlineFldNameSsn,prec->ssn,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutIntTypeRecFldIntoRecStr [ssn] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMngServiceOnlineFldNamePid,prec->pid,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutIntTypeRecFldIntoRecStr [pid] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	prec	记录指针
	sizeOfBuf	接收记录字串的缓冲的大小
输出参数:
	recStr	记录字串
返回值
	>=0		成功,拼装的记录串的长度
	<0		失败,错误码
*/
int UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec(PUnionMngServiceOnline prec,char *recStr,int sizeOfBuf)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	ret = UnionPutRecFldIntoRecStr(conMngServiceOnlineFldNameTellerNo,prec->tellerNo,strlen(prec->tellerNo),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [tellerNo] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMngServiceOnlineFldNameResID,prec->resID,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutIntTypeRecFldIntoRecStr [resID] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMngServiceOnlineFldNameTableName,prec->tableName,strlen(prec->tableName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [tableName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMngServiceOnlineFldNameServiceID,prec->serviceID,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutIntTypeRecFldIntoRecStr [serviceID] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMngServiceOnlineFldNameServiceName,prec->serviceName,strlen(prec->serviceName),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [serviceName] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMngServiceOnlineFldNameResponseCode,prec->responseCode,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutIntTypeRecFldIntoRecStr [responseCode] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMngServiceOnlineFldNameFileTransferred,prec->fileTransferred,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutIntTypeRecFldIntoRecStr [fileTransferred] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr(conMngServiceOnlineFldNameLenOfData,prec->lenOfData,recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutIntTypeRecFldIntoRecStr [lenOfData] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMngServiceOnlineFldNameData,prec->data,strlen(prec->data),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [data] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMngServiceOnlineFldNameInputDate,prec->inputDate,strlen(prec->inputDate),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [inputDate] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	ret = UnionPutRecFldIntoRecStr(conMngServiceOnlineFldNameInputTime,prec->inputTime,strlen(prec->inputTime),recStr+offset,sizeOfBuf-offset);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [inputTime] error!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	offset += ret;
	return(offset);
}


/*
功能：
	将记录字串转换为记录结构的关键字的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr(char *recStr,int lenOfRecStr,PUnionMngServiceOnline prec)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfMngServiceOnlineRec(prec);
	ret = UnionReadCharTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameDirectionTag,&(prec->directionTag));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr:: UnionReadCharTypeRecFldFromRecStr fld [directionTag] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameDate,prec->date,sizeof(prec->date));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [date] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameTime,prec->time,sizeof(prec->time));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [time] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameClientIPAddr,prec->clientIPAddr,sizeof(prec->clientIPAddr));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [clientIPAddr] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNamePort,&(prec->port));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [port] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameSsn,&(prec->ssn));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [ssn] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNamePid,&(prec->pid));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormPrimaryKeyOfMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [pid] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	return(0);
}


/*
功能：
	将记录结构转换为记录字串的函数
输入参数:
	recStr	记录字串
	lenOfRecStr	记录串长度
输出参数:
	prec	记录指针
返回值
	>=0		读出的域数目
	<0		失败,错误码
*/
int UnionFormMngServiceOnlineRecFromRecStr(char *recStr,int lenOfRecStr,PUnionMngServiceOnline prec)
{
	int	ret;
	int	offset = 0;

	if ((prec == NULL) || (recStr == NULL))
	{
		UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: prec or recStr is null!\n");
		return(UnionSetUserDefinedErrorCode(errCodeNullPointer));
	}
	UnionFormDefaultValueOfMngServiceOnlineRec(prec);
	ret = UnionReadCharTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameDirectionTag,&(prec->directionTag));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadCharTypeRecFldFromRecStr fld [directionTag] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameDate,prec->date,sizeof(prec->date));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [date] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameTime,prec->time,sizeof(prec->time));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [time] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameTellerNo,prec->tellerNo,sizeof(prec->tellerNo));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [tellerNo] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameResID,&(prec->resID));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [resID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameTableName,prec->tableName,sizeof(prec->tableName));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [tableName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameServiceID,&(prec->serviceID));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [serviceID] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameServiceName,prec->serviceName,sizeof(prec->serviceName));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [serviceName] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameResponseCode,&(prec->responseCode));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [responseCode] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameClientIPAddr,prec->clientIPAddr,sizeof(prec->clientIPAddr));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [clientIPAddr] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNamePort,&(prec->port));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [port] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameSsn,&(prec->ssn));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [ssn] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNamePid,&(prec->pid));
	if (ret < 0)
	{
		if (!0)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [pid] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameFileTransferred,&(prec->fileTransferred));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [fileTransferred] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameLenOfData,&(prec->lenOfData));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadIntTypeRecFldFromRecStr fld [lenOfData] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameData,prec->data,sizeof(prec->data));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [data] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameInputDate,prec->inputDate,sizeof(prec->inputDate));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputDate] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,conMngServiceOnlineFldNameInputTime,prec->inputTime,sizeof(prec->inputTime));
	if (ret < 0)
	{
		if (!1)
		{
			UnionUserErrLog("in UnionFormMngServiceOnlineRecFromRecStr:: UnionReadRecFldFromRecStr fld [inputTime] error!\n");
			return(UnionSetUserDefinedErrorCode(ret));
		}
	}
	return(0);
}


/*
功能：
	插入一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionInsertMngServiceOnlineRec(PUnionMngServiceOnline prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];

	//从记录拼装串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormRecStrFromMngServiceOnlineRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertMngServiceOnlineRec:: UnionFormRecStrFromMngServiceOnlineRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//赋加自动插入域
	if ((lenOfRecStr = UnionAutoAppendDBRecInputAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionInsertMngServiceOnlineRec:: UnionAutoAppendDBRecInputAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}
	//插入记录
	if ((ret = UnionInsertObjectRecord(conTBLNameMngServiceOnline,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionInsertMngServiceOnlineRec:: UnionInsertObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	删除一个记录
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionDeleteMngServiceOnlineRec(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("date",date,strlen(date),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [date] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("time",time,strlen(time),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [time] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("clientIPAddr",clientIPAddr,strlen(clientIPAddr),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [clientIPAddr] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("port",port,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [port] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("ssn",ssn,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [ssn] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("pid",pid,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [pid] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutCharTypeRecFldIntoRecStr("directionTag",directionTag,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionDeleteMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [directionTag] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	//删除记录
	if ((ret = UnionDeleteUniqueObjectRecord(conTBLNameMngServiceOnline,recStr)) < 0)
	{
		UnionUserErrLog("in UnionDeleteMngServiceOnlineRec:: UnionDeleteUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	修改一个记录
输入参数:
	prec	记录指针
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionUpdateMngServiceOnlineRec(PUnionMngServiceOnline prec)
{
	int	ret;
	int	lenOfRecStr;
	char	recStr[8192*4+1];
	char	primaryKey[1024+1];

	//从记录拼关键字
	memset(primaryKey,0,sizeof(primaryKey));
	if ((ret = UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec(prec,primaryKey,sizeof(primaryKey))) < 0)
	{
		UnionUserErrLog("in UnionUpdateMngServiceOnlineRec:: UnionFormPrimaryKeyRecStrFromMngServiceOnlineRec!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	//从记录接记录串
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec(prec,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateMngServiceOnlineRec:: UnionFormNonPrimaryKeyRecStrFromMngServiceOnlineRec!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateMngServiceOnlineRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameMngServiceOnline,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateMngServiceOnlineRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}
/*
函数功能:
	修改指定的表域:
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
	fldName 域名称
	fldValue 域值
	fldValueLen 域值长度
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateSpecFldOfMngServiceOnlineRec(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,char *fldName,char *fldValue,int lenOfFldValue)
{
	int	ret;
	char	recStr[8192*2+1];
	char	primaryKey[1024+1];
	int	lenOfRecStr = 0;

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("date",date,strlen(date),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [date] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("time",time,strlen(time),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [time] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("clientIPAddr",clientIPAddr,strlen(clientIPAddr),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [clientIPAddr] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("port",port,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [port] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("ssn",ssn,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [ssn] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("pid",pid,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [pid] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutCharTypeRecFldIntoRecStr("directionTag",directionTag,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [directionTag] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	strcpy(primaryKey,recStr);

	// 组记录
	memset(recStr,0,sizeof(recStr));
	lenOfRecStr = 0;
	if ((ret = UnionPutRecFldIntoRecStr(fldName,fldValue,lenOfFldValue,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [%s] failure!\n",fldName);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	// 修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameMngServiceOnline,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateSpecFldOfMngServiceOnlineRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}

/*
函数功能:
	修改指定的表域:
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
	fldName 域名称
	fldValue 域值
输出参数:
	无
返回值:
	>=0 成功
	<0 失败
*/
int UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,char *fldName,int fldValue)
{
	int	ret;
	char	recStr[8192*2+1];
	char	primaryKey[1024+1];
	int	lenOfRecStr = 0;

	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("date",date,strlen(date),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [date] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("time",time,strlen(time),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [time] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("clientIPAddr",clientIPAddr,strlen(clientIPAddr),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [clientIPAddr] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("port",port,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [port] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("ssn",ssn,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [ssn] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("pid",pid,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [pid] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutCharTypeRecFldIntoRecStr("directionTag",directionTag,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [directionTag] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	strcpy(primaryKey,recStr);

	// 组记录
	memset(recStr,0,sizeof(recStr));
	lenOfRecStr = 0;
	if ((ret = UnionPutIntTypeRecFldIntoRecStr(fldName,fldValue,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionPutIntTypeRecFldIntoRecStr [%s] failure!\n",fldName);
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;

	//赋加自动修改域
	if ((lenOfRecStr = UnionAutoAppendDBRecUpdateAttr(recStr,lenOfRecStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionAutoAppendDBRecUpdateAttr!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	// 修改记录
	if ((ret = UnionUpdateUniqueObjectRecord(conTBLNameMngServiceOnline,primaryKey,recStr,lenOfRecStr)) < 0)
	{
		UnionUserErrLog("in UnionUpdateIntTypeSpecFldOfMngServiceOnlineRec:: UnionUpdateUniqueObjectRecord!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}



/*
功能：
	读取一个记录
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
输出参数:
	prec	记录指针
返回值
	>=0		成功，返回记录的大小
	<0		失败,错误码
*/
int UnionReadMngServiceOnlineRec(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,PUnionMngServiceOnline prec)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("date",date,strlen(date),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [date] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("time",time,strlen(time),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [time] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("clientIPAddr",clientIPAddr,strlen(clientIPAddr),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [clientIPAddr] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("port",port,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [port] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("ssn",ssn,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [ssn] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("pid",pid,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [pid] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutCharTypeRecFldIntoRecStr("directionTag",directionTag,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: UnionPutRecFldIntoRecStr [directionTag] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameMngServiceOnline,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//从记录串拼装结构
	if ((ret = UnionFormMngServiceOnlineRecFromRecStr(recStr,lenOfRecStr,prec)) < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRec:: UnionFormMngServiceOnlineRecFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(sizeof(*prec));
}


/*
功能：
	读取一个记录
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
	fldName		域名
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadMngServiceOnlineRecIntTypeFld(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,char *fldName,int *fldValue)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("date",date,strlen(date),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: UnionPutRecFldIntoRecStr [date] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("time",time,strlen(time),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: UnionPutRecFldIntoRecStr [time] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("clientIPAddr",clientIPAddr,strlen(clientIPAddr),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: UnionPutRecFldIntoRecStr [clientIPAddr] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("port",port,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: UnionPutRecFldIntoRecStr [port] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("ssn",ssn,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: UnionPutRecFldIntoRecStr [ssn] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("pid",pid,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: UnionPutRecFldIntoRecStr [pid] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutCharTypeRecFldIntoRecStr("directionTag",directionTag,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: UnionPutRecFldIntoRecStr [directionTag] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameMngServiceOnline,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//读指定域
	if ((ret = UnionReadIntTypeRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue)) < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecIntTypeFld:: UnionReadIntTypeRecFldFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	读取一个记录
输入参数:
	date 数据
	time 数据
	clientIPAddr 
	port 
	ssn 服务流水号
	pid 处理进程号
	directionTag 1位的请求标识,值固定为1
	fldName		域名
	sizeOfBuf	域值缓冲大小
输出参数:
	fldValue	域值
返回值
	>=0		成功，返回域值的长度
	<0		失败,错误码
*/
int UnionReadMngServiceOnlineRecFld(char *date,char *time,char *clientIPAddr,int port,int ssn,int pid,char directionTag,char *fldName,char *fldValue,int sizeOfBuf)
{
	int	ret;
	int	lenOfRecStr = 0;
	char	recStr[8192*4+1];
	char	condition[1024+1];

	//从记录拼装串
	// 拼关键字
	memset(recStr,0,sizeof(recStr));
	ret = UnionPutRecFldIntoRecStr("date",date,strlen(date),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: UnionPutRecFldIntoRecStr [date] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("time",time,strlen(time),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: UnionPutRecFldIntoRecStr [time] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutRecFldIntoRecStr("clientIPAddr",clientIPAddr,strlen(clientIPAddr),recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: UnionPutRecFldIntoRecStr [clientIPAddr] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("port",port,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: UnionPutRecFldIntoRecStr [port] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("ssn",ssn,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: UnionPutRecFldIntoRecStr [ssn] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutIntTypeRecFldIntoRecStr("pid",pid,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: UnionPutRecFldIntoRecStr [pid] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	ret = UnionPutCharTypeRecFldIntoRecStr("directionTag",directionTag,recStr+lenOfRecStr,sizeof(recStr)-lenOfRecStr);
	if (ret < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: UnionPutRecFldIntoRecStr [directionTag] failure!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}
	lenOfRecStr += ret;
	if (lenOfRecStr >= sizeof(condition))
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: lenOfCondition = [%d] too long!\n",lenOfRecStr);
		return(ret);
	}
	memset(condition,0,sizeof(condition));
	memcpy(condition,recStr,lenOfRecStr);

	//读取记录
	memset(recStr,0,sizeof(recStr));
	if ((lenOfRecStr = UnionSelectUniqueObjectRecordByPrimaryKey(conTBLNameMngServiceOnline,condition,recStr,sizeof(recStr))) < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: UnionSelectUniqueObjectRecordByPrimaryKey!\n");
		return(UnionSetUserDefinedErrorCode(lenOfRecStr));
	}

	//读指定域
	if ((ret = UnionReadRecFldFromRecStr(recStr,lenOfRecStr,fldName,fldValue,sizeOfBuf)) < 0)
	{
		UnionUserErrLog("in UnionReadMngServiceOnlineRecFld:: UnionReadRecFldFromRecStr!\n");
		return(UnionSetUserDefinedErrorCode(ret));
	}

	return(ret);
}


/*
功能：
	根据条件，批量读取数据
输入参数:
	condition	条件字串
	maxRecNum		读取的最大记录数量
输出参数:
	recGrp		记录数组
返回值
	>=0		成功,读取的记录数量
	<0		失败,错误码
*/
int UnionBatchReadMngServiceOnlineRec(char *condition,TUnionMngServiceOnline recGrp[],int maxRecNum)
{
	int	ret;
	char	fileName[512+1];
	int	recNum = 0;
	FILE	*recFileFp = NULL;
	char	recStr[8192*2+1];
	int	lenOfRecStr;
	char	tableName[128+1];
	TUnionMngServiceOnline	rec;

	memset(fileName,0,sizeof(fileName));
	sprintf(fileName,"%s/pid-%d.tmp",getenv("UNIONTEMP"),getpid());

// 读所有记录
	if ((ret = UnionBatchSelectObjectRecord(conTBLNameMngServiceOnline,condition,fileName)) < 0)
	{
		UnionUserErrLog("in UnionBatchReadMngServiceOnlineRec:: UnionBatchSelectObjectRecord from [%s] on [%s]!\n",conTBLNameMngServiceOnline,condition);
		return(ret);
	}
	// 打开文件
	if ((recFileFp = fopen(fileName,"r")) == NULL)
	{
		UnionUserErrLog("in UnionBatchReadMngServiceOnlineRec:: fopen [%s]\n",fileName);
		goto errExit;
	}
	while (!feof(recFileFp))
	{
		if (recNum >= maxRecNum)
		{
			UnionLog("in UnionBatchReadMngServiceOnlineRec:: still exists records satisfy the condition [%s]!\n",condition);
			ret = recNum;
			goto errExit;
		}
		memset(recStr,0,sizeof(recStr));
		if ((lenOfRecStr = UnionReadOneDataLineFromTxtFile(recFileFp,recStr,sizeof(recStr))) <= 0)
			continue;
		memset(&rec,0,sizeof(rec));
		if ((ret = UnionFormMngServiceOnlineRecFromRecStr(recStr,lenOfRecStr,&rec)) < 0)
		{
			UnionUserErrLog("in UnionBatchReadMngServiceOnlineRec:: UnionFormMngServiceOnlineRecFromRecStr from [%04d] [%s]\n",lenOfRecStr,recStr);
			goto errExit;
		}
		memcpy(&(recGrp[recNum]),&rec,sizeof(rec));
		recNum++;
	}
	ret = recNum;
errExit:
	fclose(recFileFp);
	UnionDeleteFile(fileName);
	return(ret);

}
